// Kiro-account-manager/src/renderer/src/components/accounts/EditAccountDialog.tsx
import { useState, useEffect } from 'react'
import { X, Loader2, RefreshCw, Download, CheckCircle, Copy, Check } from 'lucide-react'
import { Button, Card, CardContent, CardHeader, CardTitle } from '../ui'
import { useAccountsStore } from '@/store'
import { useTranslation } from '@/hooks/useTranslation'
import type { Account, SubscriptionType } from '@shared/types/account'

interface EditAccountDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  account: Account | null
}

export function EditAccountDialog({
  open,
  onOpenChange,
  account
}: EditAccountDialogProps) {
  const { updateAccount } = useAccountsStore()
  const { t } = useTranslation()
  const isEn = t('common.unknown') === 'Unknown'

  // OIDC 凭证（核心）
  const [refreshToken, setRefreshToken] = useState('')
  const [clientId, setClientId] = useState('')
  const [clientSecret, setClientSecret] = useState('')
  const [region, setRegion] = useState('us-east-1')

  // 可编辑字段
  const [nickname, setNickname] = useState('')

  // 自动获取的信息（只读显示）
  const [accountInfo, setAccountInfo] = useState<{
    email: string
    userId: string
    accessToken: string
    subscriptionType: string
    subscriptionTitle: string
    usage: { 
      current: number
      limit: number
      baseLimit?: number
      baseCurrent?: number
      freeTrialLimit?: number
      freeTrialCurrent?: number
      freeTrialExpiry?: string
      bonuses?: { code: string; name: string; current: number; limit: number; expiresAt?: string }[]
      nextResetDate?: string
    }
    daysRemaining?: number
    expiresAt?: number
  } | null>(null)

  // 状态
  const [isVerifying, setIsVerifying] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [copiedToken, setCopiedToken] = useState(false)

  const handleCopyAccessToken = (): void => {
    if (accountInfo?.accessToken) {
      navigator.clipboard.writeText(accountInfo.accessToken)
      setCopiedToken(true)
      setTimeout(() => setCopiedToken(false), 2000)
    }
  }

  // 当账号变化时更新表单
  useEffect(() => {
    if (account) {
      setRefreshToken(account.credentials.refreshToken || '')
      setClientId(account.credentials.clientId || '')
      setClientSecret(account.credentials.clientSecret || '')
      setRegion(account.credentials.region || 'us-east-1')
      setNickname(account.nickname || '')
      
      // 设置当前账号信息
      setAccountInfo({
        email: account.email,
        userId: account.userId || '',
        accessToken: account.credentials.accessToken,
        subscriptionType: account.subscription.type,
        subscriptionTitle: account.subscription.title || account.subscription.type,
        usage: {
          current: account.usage?.current || 0,
          limit: account.usage?.limit || 0
        },
        daysRemaining: account.subscription.daysRemaining,
        expiresAt: account.subscription.expiresAt
      })
      setError(null)
    }
  }, [account])

  // 从本地配置导入
  const handleImportFromLocal = async () => {
    try {
      const result = await window.api.loadKiroCredentials()
      if (result.success && result.data) {
        setRefreshToken(result.data.refreshToken)
        setClientId(result.data.clientId)
        setClientSecret(result.data.clientSecret)
        setRegion(result.data.region)
        setError(null)
      } else {
        setError(result.error || '导入失败')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : '导入失败')
    }
  }

  // 验证并刷新信息
  const handleVerifyAndRefresh = async () => {
    const isSocial = account?.credentials.authMethod === 'social'
    if (!refreshToken) {
      setError('请填写 Refresh Token')
      return
    }
    if (!isSocial && (!clientId || !clientSecret)) {
      setError('请填写 Client ID 和 Client Secret')
      return
    }

    setIsVerifying(true)
    setError(null)

    try {
      const result = await window.api.verifyAccountCredentials({
        refreshToken,
        clientId,
        clientSecret,
        region,
        authMethod: account?.credentials.authMethod,
        provider: account?.credentials.provider || account?.idp
      })

      if (result.success && result.data) {
        setAccountInfo({
          email: result.data.email,
          userId: result.data.userId,
          accessToken: result.data.accessToken,
          subscriptionType: result.data.subscriptionType,
          subscriptionTitle: result.data.subscriptionTitle,
          usage: result.data.usage,
          daysRemaining: result.data.daysRemaining,
          expiresAt: result.data.expiresAt
        })
        // 更新 refreshToken（可能返回新的）
        if (result.data.refreshToken) {
          setRefreshToken(result.data.refreshToken)
        }
      } else {
        setError(result.error || '验证失败')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : '验证失败')
    } finally {
      setIsVerifying(false)
    }
  }

  // 保存
  const handleSave = () => {
    if (!account || !accountInfo) return

    const now = Date.now()

    updateAccount(account.id, {
      email: accountInfo.email,
      userId: accountInfo.userId,
      nickname: nickname || undefined,
      credentials: {
        ...account.credentials,
        accessToken: accountInfo.accessToken,
        csrfToken: '',
        refreshToken,
        clientId,
        clientSecret,
        region,
        expiresAt: now + 3600 * 1000
      },
      subscription: {
        type: accountInfo.subscriptionType as SubscriptionType,
        title: accountInfo.subscriptionTitle,
        daysRemaining: accountInfo.daysRemaining,
        expiresAt: accountInfo.expiresAt
      },
      usage: {
        current: accountInfo.usage.current,
        limit: accountInfo.usage.limit,
        percentUsed: accountInfo.usage.limit > 0 
          ? accountInfo.usage.current / accountInfo.usage.limit 
          : 0,
        lastUpdated: now,
        baseLimit: accountInfo.usage.baseLimit,
        baseCurrent: accountInfo.usage.baseCurrent,
        freeTrialLimit: accountInfo.usage.freeTrialLimit,
        freeTrialCurrent: accountInfo.usage.freeTrialCurrent,
        freeTrialExpiry: accountInfo.usage.freeTrialExpiry,
        bonuses: accountInfo.usage.bonuses,
        nextResetDate: accountInfo.usage.nextResetDate
      },
      status: 'active'
    })

    onOpenChange(false)
  }

  if (!open || !account) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={() => onOpenChange(false)} />

      <Card className="relative w-full max-w-lg max-h-[90vh] overflow-auto z-10 animate-in zoom-in-95 duration-200">
        {/* 头部 */}
        <CardHeader className="pb-4 border-b sticky top-0 bg-background z-20">
          <div className="flex items-center justify-between">
            <CardTitle className="text-xl font-bold">{isEn ? 'Edit Account' : '编辑账号'}</CardTitle>
            <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full hover:bg-red-500 hover:text-white transition-colors" onClick={() => onOpenChange(false)}>
              <X className="h-4 w-4" />
            </Button>
          </div>
          <p className="text-sm text-muted-foreground mt-1">{isEn ? 'Modify account settings or update credentials' : '修改账号配置或更新凭证'}</p>
        </CardHeader>

        <CardContent className="p-6 space-y-6">
          {/* 当前账号信息 */}
          {accountInfo && (
            <div className="p-4 bg-primary/5 rounded-xl border border-primary/10 space-y-3">
              <div className="flex items-center justify-between border-b border-primary/10 pb-2">
                <span className="text-sm font-semibold text-foreground/80">{isEn ? 'Account Status' : '当前账号状态'}</span>
                <div className="px-2.5 py-0.5 rounded-full bg-success/10 text-success text-xs font-medium flex items-center gap-1.5">
                  <CheckCircle className="h-3.5 w-3.5" />
                  {isEn ? 'Verified' : '已验证'}
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-muted-foreground text-xs block mb-1">{isEn ? 'Email' : '邮箱'}</span>
                  <span className="font-medium font-mono text-xs truncate block" title={accountInfo.email}>{accountInfo.email}</span>
                </div>
                <div>
                  <span className="text-muted-foreground text-xs block mb-1">{isEn ? 'Plan' : '订阅计划'}</span>
                  <span className="font-medium">{accountInfo.subscriptionTitle}</span>
                </div>
                <div>
                  <span className="text-muted-foreground text-xs block mb-1">{isEn ? 'Usage' : '使用额度'}</span>
                  <span className="font-medium">
                    {accountInfo.usage.current.toLocaleString()} / {accountInfo.usage.limit.toLocaleString()}
                  </span>
                </div>
                <div>
                  <span className="text-muted-foreground text-xs block mb-1">{isEn ? 'Days Left' : '剩余天数'}</span>
                  <span className="font-medium">{accountInfo.daysRemaining ?? '-'} {isEn ? 'd' : '天'}</span>
                </div>
              </div>
            </div>
          )}

          {/* 别名 */}
          <div className="space-y-2">
            <label className="text-sm font-medium">{isEn ? 'Nickname' : '账号别名'}</label>
            <input
              type="text"
              value={nickname}
              onChange={(e) => setNickname(e.target.value)}
              placeholder={isEn ? 'Give this account a memorable name' : '给这个账号起个好记的名字'}
              className="w-full h-10 px-3 py-2 text-sm rounded-xl border border-input bg-background/50 ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"
            />
          </div>

          {/* 凭证配置 */}
          <div className="space-y-5 pt-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-semibold">
                  {account?.credentials.authMethod === 'social' ? (isEn ? 'Social Login' : '社交登录凭证') : (isEn ? 'OIDC Credentials' : 'OIDC 凭证配置')}
                </h3>
                {account?.credentials.authMethod === 'social' && (
                  <span className="px-2 py-0.5 text-xs rounded-full bg-primary/10 text-primary">
                    {account?.credentials.provider || account?.idp}
                  </span>
                )}
              </div>
              {account?.credentials.authMethod !== 'social' && (
                <Button 
                  type="button" 
                  variant="outline" 
                  size="sm"
                  className="h-8 rounded-lg text-xs"
                  onClick={handleImportFromLocal}
                >
                  <Download className="h-3 w-3 mr-1.5" />
                  {isEn ? 'Import Local' : '从本地导入'}
                </Button>
              )}
            </div>

            {account?.credentials.authMethod === 'social' && (
              <p className="text-xs text-muted-foreground">
                {isEn ? 'Social login only needs Refresh Token' : '社交登录账号只需要 Refresh Token，不需要 Client ID 和 Client Secret'}
              </p>
            )}

            <div className="space-y-4">
              {/* Access Token (只读，可复制) */}
              {accountInfo?.accessToken && (
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <label className="text-sm font-medium">Access Token</label>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="h-7 px-2 text-xs"
                      onClick={handleCopyAccessToken}
                    >
                      {copiedToken ? <Check className="h-3 w-3 mr-1 text-success" /> : <Copy className="h-3 w-3 mr-1" />}
                      {copiedToken ? (isEn ? 'Copied' : '已复制') : (isEn ? 'Copy' : '复制')}
                    </Button>
                  </div>
                  <div className="w-full px-3 py-2.5 text-sm rounded-xl border border-input bg-muted/50 font-mono text-muted-foreground truncate">
                    {accountInfo.accessToken.slice(0, 50)}...
                  </div>
                </div>
              )}

              <div className="space-y-2">
                <label className="text-sm font-medium">
                  Refresh Token <span className="text-destructive">*</span>
                </label>
                <textarea
                  value={refreshToken}
                  onChange={(e) => setRefreshToken(e.target.value)}
                  placeholder="aorAAAAA..."
                  className="w-full min-h-[80px] px-3 py-2.5 text-sm rounded-xl border border-input bg-background/50 ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 resize-none font-mono"
                />
              </div>

              {account?.credentials.authMethod !== 'social' && (
                <>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <label className="text-sm font-medium">
                        Client ID <span className="text-destructive">*</span>
                      </label>
                      <input
                        type="text"
                        value={clientId}
                        onChange={(e) => setClientId(e.target.value)}
                        placeholder="Client ID"
                        className="w-full h-10 px-3 py-2 text-sm rounded-xl border border-input bg-background/50 ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 font-mono"
                      />
                    </div>

                    <div className="space-y-2">
                      <label className="text-sm font-medium">
                        Client Secret <span className="text-destructive">*</span>
                      </label>
                      <input
                        type="text"
                        value={clientSecret}
                        onChange={(e) => setClientSecret(e.target.value)}
                        placeholder="Client Secret"
                        className="w-full h-10 px-3 py-2 text-sm rounded-xl border border-input bg-background/50 ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 font-mono"
                      />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="text-sm font-medium">AWS Region</label>
                    <select
                      value={region}
                      onChange={(e) => setRegion(e.target.value)}
                      className="w-full h-10 px-3 py-2 text-sm rounded-xl border border-input bg-background/50 ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"
                    >
                      <option value="us-east-1">us-east-1 (N. Virginia)</option>
                      <option value="us-west-2">us-west-2 (Oregon)</option>
                      <option value="eu-west-1">eu-west-1 (Ireland)</option>
                    </select>
                  </div>
                </>
              )}

              <Button 
                type="button" 
                variant="secondary"
                className="w-full h-10 rounded-xl font-medium"
                onClick={handleVerifyAndRefresh}
                disabled={isVerifying || !refreshToken || (account?.credentials.authMethod !== 'social' && (!clientId || !clientSecret))}
              >
                {isVerifying ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <RefreshCw className="h-4 w-4 mr-2" />
                )}
                {isEn ? 'Verify & Refresh' : '验证并刷新凭证信息'}
              </Button>
            </div>
          </div>

          {/* 错误信息 */}
          {error && (
            <div className="p-3 bg-destructive/10 text-destructive rounded-xl text-sm flex items-center gap-2 animate-in fade-in slide-in-from-top-2">
              <div className="w-1.5 h-1.5 rounded-full bg-destructive shrink-0" />
              {error}
            </div>
          )}
        </CardContent>

        {/* 底部按钮 */}
        <div className="sticky bottom-0 bg-background/95 backdrop-blur p-4 border-t flex justify-end gap-3 z-20">
          <Button variant="outline" onClick={() => onOpenChange(false)} className="rounded-xl h-10 px-6">
            {isEn ? 'Cancel' : '取消'}
          </Button>
          <Button onClick={handleSave} disabled={!accountInfo} className="rounded-xl h-10 px-6">
            {isEn ? 'Save Changes' : '保存更改'}
          </Button>
        </div>
      </Card>
    </div>
  )
}

// Kiro-account-manager/src/renderer-vue/src/components/accounts/EditAccountDialog.vue
<script setup>
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import {
    UiAlert,
    UiBadge,
    UiButton,
    UiCard,
    UiDialog,
    UiField,
    UiInput,
    UiSelect,
    UiTextarea
} from '@lingyzh/ui'
import { Check, Clipboard, Download, RefreshCw } from 'lucide-vue-next'
import { useTranslation } from '../../composables/useTranslation'
import { toIpcData } from '../../lib/ipcData'
import { useAccountsStore } from '../../stores/accounts'

const props = defineProps({
    open: { type: Boolean, required: true },
    account: { type: Object, default: null }
})
const emit = defineEmits(['update:open'])
const { actualLanguage } = useTranslation()
const isEn = computed(() => actualLanguage.value === 'en')
const accounts = useAccountsStore()
const refreshToken = ref('')
const clientId = ref('')
const clientSecret = ref('')
const region = ref('us-east-1')
const nickname = ref('')
const accountInfo = ref(null)
const verifying = ref(false)
const importing = ref(false)
const copied = ref(false)
const error = ref('')
let generation = 0
let copyTimer = null
let active = true
const social = computed(() => props.account?.credentials?.authMethod === 'social')

function clearCopyTimer() {
    if (copyTimer) clearTimeout(copyTimer)
    copyTimer = null
    copied.value = false
}

function resetForm(account) {
    generation += 1
    verifying.value = false
    importing.value = false
    clearCopyTimer()
    error.value = ''
    if (!account) {
        refreshToken.value = ''
        clientId.value = ''
        clientSecret.value = ''
        region.value = 'us-east-1'
        nickname.value = ''
        accountInfo.value = null
        return
    }
    refreshToken.value = account.credentials?.refreshToken || ''
    clientId.value = account.credentials?.clientId || ''
    clientSecret.value = account.credentials?.clientSecret || ''
    region.value = account.credentials?.region || 'us-east-1'
    nickname.value = account.nickname || ''
    accountInfo.value = {
        email: account.email,
        userId: account.userId || '',
        accessToken: account.credentials?.accessToken || '',
        subscriptionType: account.subscription?.type || '',
        subscriptionTitle: account.subscription?.title || account.subscription?.type || '',
        usage: {
            current: account.usage?.current || 0,
            limit: account.usage?.limit || 0
        },
        daysRemaining: account.subscription?.daysRemaining,
        expiresAt: account.subscription?.expiresAt
    }
}

function requestClose() {
    if (!active || !props.open) return
    generation += 1
    verifying.value = false
    importing.value = false
    clearCopyTimer()
    emit('update:open', false)
}

function copyAccessToken() {
    if (!active || !props.open || !accountInfo.value?.accessToken) return
    const token = accountInfo.value.accessToken
    const current = generation
    Promise.resolve()
        .then(() => navigator.clipboard.writeText(token))
        .then(() => {
            if (!active || !props.open || current !== generation) return
            clearCopyTimer()
            copied.value = true
            copyTimer = setTimeout(() => {
                if (active && current === generation) copied.value = false
                copyTimer = null
            }, 2000)
        })
        .catch((cause) => {
            if (active && props.open && current === generation)
                error.value = cause instanceof Error ? cause.message : String(cause)
        })
}

function importLocal() {
    if (!active || !props.open || !props.account || importing.value || verifying.value) return
    const current = generation
    importing.value = true
    error.value = ''
    Promise.resolve()
        .then(() => {
            if (!active || !props.open || current !== generation) return null
            return window.api.loadKiroCredentials()
        })
        .then((result) => {
            if (!active || !props.open || current !== generation || !result) return
            if (!result.success || !result.data) {
                error.value = result.error || (isEn.value ? 'Import failed' : '导入失败')
                return
            }
            refreshToken.value = result.data.refreshToken
            clientId.value = result.data.clientId
            clientSecret.value = result.data.clientSecret
            region.value = result.data.region
        })
        .catch((cause) => {
            if (active && props.open && current === generation)
                error.value = cause instanceof Error ? cause.message : String(cause)
        })
        .finally(() => {
            if (active && current === generation) importing.value = false
        })
}

function verify() {
    if (!active || !props.open || !props.account || verifying.value || importing.value) return
    if (!refreshToken.value) {
        error.value = isEn.value ? 'Please enter Refresh Token' : '请填写 Refresh Token'
        return
    }
    if (!social.value && (!clientId.value || !clientSecret.value)) {
        error.value = isEn.value
            ? 'Please enter Client ID and Client Secret'
            : '请填写 Client ID 和 Client Secret'
        return
    }
    const current = generation
    const credentials = toIpcData({
        refreshToken: refreshToken.value,
        clientId: clientId.value,
        clientSecret: clientSecret.value,
        region: region.value,
        authMethod: props.account.credentials?.authMethod,
        provider: props.account.credentials?.provider || props.account.idp
    })
    verifying.value = true
    error.value = ''
    Promise.resolve()
        .then(() => {
            if (!active || !props.open || current !== generation) return null
            return window.api.verifyAccountCredentials(credentials)
        })
        .then((result) => {
            if (!active || !props.open || current !== generation || !result) return
            if (!result.success || !result.data) {
                error.value = result.error || (isEn.value ? 'Verification failed' : '验证失败')
                return
            }
            accountInfo.value = {
                email: result.data.email,
                userId: result.data.userId,
                accessToken: result.data.accessToken,
                subscriptionType: result.data.subscriptionType,
                subscriptionTitle: result.data.subscriptionTitle,
                usage: result.data.usage,
                daysRemaining: result.data.daysRemaining,
                expiresAt: result.data.expiresAt
            }
            if (result.data.refreshToken) refreshToken.value = result.data.refreshToken
        })
        .catch((cause) => {
            if (active && props.open && current === generation)
                error.value = cause instanceof Error ? cause.message : String(cause)
        })
        .finally(() => {
            if (active && current === generation) verifying.value = false
        })
}

function save() {
    if (
        !active ||
        !props.open ||
        !props.account ||
        !accountInfo.value ||
        verifying.value ||
        importing.value
    )
        return
    const now = Date.now()
    const info = accountInfo.value
    const usage = info.usage || { current: 0, limit: 0 }
    try {
        accounts.updateAccount(props.account.id, {
            email: info.email,
            userId: info.userId,
            nickname: nickname.value || undefined,
            credentials: {
                ...props.account.credentials,
                accessToken: info.accessToken,
                csrfToken: '',
                refreshToken: refreshToken.value,
                clientId: clientId.value,
                clientSecret: clientSecret.value,
                region: region.value,
                expiresAt: now + 3600 * 1000
            },
            subscription: {
                type: info.subscriptionType,
                title: info.subscriptionTitle,
                daysRemaining: info.daysRemaining,
                expiresAt: info.expiresAt
            },
            usage: {
                current: usage.current,
                limit: usage.limit,
                percentUsed: usage.limit > 0 ? usage.current / usage.limit : 0,
                lastUpdated: now,
                baseLimit: usage.baseLimit,
                baseCurrent: usage.baseCurrent,
                freeTrialLimit: usage.freeTrialLimit,
                freeTrialCurrent: usage.freeTrialCurrent,
                freeTrialExpiry: usage.freeTrialExpiry,
                bonuses: usage.bonuses,
                nextResetDate: usage.nextResetDate
            },
            status: 'active'
        })
        requestClose()
    } catch (cause) {
        error.value = cause instanceof Error ? cause.message : String(cause)
    }
}

watch(() => props.account, resetForm, { immediate: true })
watch(
    () => props.open,
    (open) => {
        if (!open) {
            generation += 1
            verifying.value = false
            importing.value = false
            clearCopyTimer()
        }
    }
)
onBeforeUnmount(() => {
    active = false
    generation += 1
    clearCopyTimer()
})
</script>

<template>
    <UiDialog
        :open="open && Boolean(account)"
        size="lg"
        scrollable
        :aria-label="isEn ? 'Edit Account' : '编辑账号'"
        :content-label="isEn ? 'Account credentials and information' : '账号凭证和信息'"
        @update:open="requestClose"
    >
        <template #header>
            <div>
                <h2 class="ui-card-title">{{ isEn ? 'Edit Account' : '编辑账号' }}</h2>
                <p class="kam-muted">
                    {{
                        isEn
                            ? 'Modify account settings or update credentials'
                            : '修改账号配置或更新凭证'
                    }}
                </p>
            </div>
        </template>
        <div v-if="account" class="kam-dialog-content">
            <UiCard v-if="accountInfo" density="compact">
                <div class="edit-summary">
                    <div class="edit-heading">
                        <strong>{{ isEn ? 'Account Status' : '当前账号状态' }}</strong>
                        <UiBadge tone="success">{{ isEn ? 'Verified' : '已验证' }}</UiBadge>
                    </div>
                    <div class="kam-field-grid">
                        <div>
                            <span class="kam-muted">{{ isEn ? 'Email' : '邮箱' }}</span>
                            <p class="kam-mono">{{ accountInfo.email }}</p>
                        </div>
                        <div>
                            <span class="kam-muted">{{ isEn ? 'Plan' : '订阅计划' }}</span>
                            <p>{{ accountInfo.subscriptionTitle }}</p>
                        </div>
                        <div>
                            <span class="kam-muted">{{ isEn ? 'Usage' : '使用额度' }}</span>
                            <p>
                                {{ accountInfo.usage.current.toLocaleString() }} /
                                {{ accountInfo.usage.limit.toLocaleString() }}
                            </p>
                        </div>
                        <div>
                            <span class="kam-muted">{{ isEn ? 'Days Left' : '剩余天数' }}</span>
                            <p>{{ accountInfo.daysRemaining ?? '-' }} {{ isEn ? 'd' : '天' }}</p>
                        </div>
                    </div>
                </div>
            </UiCard>
            <UiField
                v-slot="{ controlAttrs }"
                class="edit-field"
                :label="isEn ? 'Nickname' : '账号别名'"
                for="account-edit-nickname"
            >
                <UiInput
                    v-model="nickname"
                    v-bind="controlAttrs"
                    :disabled="verifying || importing"
                    data-testid="account-edit-nickname"
                />
            </UiField>
            <div class="edit-heading">
                <div class="kam-actions">
                    <strong>{{
                        social
                            ? isEn
                                ? 'Social Login'
                                : '社交登录凭证'
                            : isEn
                              ? 'OIDC Credentials'
                              : 'OIDC 凭证配置'
                    }}</strong>
                    <UiBadge v-if="social" tone="accent">{{
                        account.credentials.provider || account.idp
                    }}</UiBadge>
                </div>
                <UiButton
                    v-if="!social"
                    size="sm"
                    :loading="importing"
                    :disabled="verifying"
                    data-testid="account-edit-import-local"
                    @click="importLocal"
                >
                    <Download :size="16" />{{ isEn ? 'Import Local' : '从本地导入' }}
                </UiButton>
            </div>
            <p v-if="social" class="kam-muted">
                {{
                    isEn
                        ? 'Social login only needs Refresh Token'
                        : '社交登录账号只需要 Refresh Token'
                }}
            </p>
            <div v-if="accountInfo?.accessToken" class="edit-summary">
                <div class="edit-heading">
                    <strong>Access Token</strong>
                    <UiButton
                        size="sm"
                        variant="ghost"
                        data-testid="account-edit-copy-access"
                        @click="copyAccessToken"
                    >
                        <Check v-if="copied" :size="16" /><Clipboard v-else :size="16" />{{
                            copied ? (isEn ? 'Copied' : '已复制') : isEn ? 'Copy' : '复制'
                        }}
                    </UiButton>
                </div>
                <code class="kam-mono">{{ accountInfo.accessToken.slice(0, 50) }}...</code>
            </div>
            <UiField
                v-slot="{ controlAttrs }"
                class="edit-field"
                label="Refresh Token *"
                for="account-edit-refresh-token"
            >
                <UiTextarea
                    v-model="refreshToken"
                    v-bind="controlAttrs"
                    :rows="3"
                    :disabled="verifying || importing"
                    data-testid="account-edit-refresh-token"
                />
            </UiField>
            <template v-if="!social">
                <UiField
                    v-slot="{ controlAttrs }"
                    class="edit-field"
                    label="Client ID *"
                    for="account-edit-client-id"
                >
                    <UiInput
                        v-model="clientId"
                        v-bind="controlAttrs"
                        :disabled="verifying || importing"
                        data-testid="account-edit-client-id"
                    />
                </UiField>
                <UiField
                    v-slot="{ controlAttrs }"
                    class="edit-field"
                    label="Client Secret *"
                    for="account-edit-client-secret"
                >
                    <UiInput
                        v-model="clientSecret"
                        v-bind="controlAttrs"
                        :disabled="verifying || importing"
                        data-testid="account-edit-client-secret"
                    />
                </UiField>
                <UiField
                    v-slot="{ controlAttrs }"
                    class="edit-field"
                    label="AWS Region"
                    for="account-edit-region"
                >
                    <UiSelect
                        v-model="region"
                        v-bind="controlAttrs"
                        :disabled="verifying || importing"
                        data-testid="account-edit-region"
                    >
                        <option value="us-east-1">us-east-1 (N. Virginia)</option>
                        <option value="us-west-2">us-west-2 (Oregon)</option>
                        <option value="eu-west-1">eu-west-1 (Ireland)</option>
                    </UiSelect>
                </UiField>
            </template>
            <div class="kam-actions">
                <UiButton
                    :loading="verifying"
                    :disabled="
                        importing || !refreshToken || (!social && (!clientId || !clientSecret))
                    "
                    data-testid="account-edit-verify"
                    @click="verify"
                >
                    <RefreshCw :size="16" />{{ isEn ? 'Verify & Refresh' : '验证并刷新凭证信息' }}
                </UiButton>
            </div>
            <UiAlert v-if="error" tone="error" data-testid="account-edit-error">{{
                error
            }}</UiAlert>
        </div>
        <template #footer>
            <div class="kam-actions">
                <UiButton
                    :disabled="verifying || importing"
                    data-testid="account-edit-cancel"
                    @click="requestClose"
                    >{{ isEn ? 'Cancel' : '取消' }}</UiButton
                >
                <UiButton
                    variant="primary"
                    :disabled="!accountInfo || verifying || importing"
                    data-testid="account-edit-save"
                    @click="save"
                    >{{ isEn ? 'Save Changes' : '保存更改' }}</UiButton
                >
            </div>
        </template>
    </UiDialog>
</template>

<style scoped>
.edit-heading {
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 8px;
}
.edit-summary {
    display: flex;
    flex-direction: column;
    gap: 12px;
}
.edit-summary p {
    margin: 0;
}
.edit-field {
    flex-direction: column;
    align-items: stretch;
    gap: 6px;
}
.edit-field :deep(.ui-input),
.edit-field :deep(.ui-textarea),
.edit-field :deep(.ui-select) {
    width: 100%;
}
</style>
