// Kiro-account-manager/src/renderer-vue/src/components/accounts/AccountFilter.vue
<script setup>
import { computed, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { UiBadge, UiButton, UiCard, UiField, UiInput } from '@lingyzh/ui'
import { toRgba } from '@shared/lib/accountHelpers'
import { useAccountsStore } from '../../stores/accounts'
import { useTranslation } from '../../composables/useTranslation'

const DOMAIN_DISPLAY_LIMIT = 16
const subscriptionOptions = [
    { value: 'Free', label: 'KIRO FREE' },
    { value: 'Pro', label: 'KIRO PRO' },
    { value: 'Pro_Plus', label: 'KIRO PRO+' },
    { value: 'Enterprise', label: 'KIRO POWER' }
]
const statusOptions = [
    { value: 'active', zh: '正常', en: 'Active' },
    { value: 'expired', zh: '已过期', en: 'Expired' },
    { value: 'error', zh: '错误', en: 'Error' },
    { value: 'unknown', zh: '未知', en: 'Unknown' }
]
const idpOptions = [
    { value: 'Google', label: 'Google' },
    { value: 'Github', label: 'GitHub' },
    { value: 'BuilderId', label: 'BuilderId' },
    { value: 'Enterprise', label: 'Enterprise' },
    { value: 'AWSIdC', label: 'AWSIdC' }
]

const accountsStore = useAccountsStore()
const { accounts, filter, tags } = storeToRefs(accountsStore)
const { actualLanguage } = useTranslation()
const isEn = computed(() => actualLanguage.value === 'en')
const stats = computed(() => accountsStore.getStats())
const showAllDomains = ref(false)

const domainCounts = computed(() => {
    const counts = new Map()
    for (const account of accounts.value.values()) {
        const atIndex = account.email.lastIndexOf('@')
        if (atIndex < 0) continue
        const domain = account.email.slice(atIndex + 1).toLowerCase()
        if (!domain) continue
        counts.set(domain, (counts.get(domain) ?? 0) + 1)
    }
    return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
})

const visibleDomains = computed(() => {
    if (showAllDomains.value || domainCounts.value.length <= DOMAIN_DISPLAY_LIMIT)
        return domainCounts.value
    const top = domainCounts.value.slice(0, DOMAIN_DISPLAY_LIMIT)
    const selected = new Set(filter.value.emailDomains ?? [])
    for (const entry of domainCounts.value.slice(DOMAIN_DISPLAY_LIMIT)) {
        if (selected.has(entry[0])) top.push(entry)
    }
    return top
})

const hasActiveFilters = computed(() =>
    Boolean(
        filter.value.subscriptionTypes?.length ||
        filter.value.statuses?.length ||
        filter.value.idps?.length ||
        filter.value.groupIds?.length ||
        filter.value.tagIds?.length ||
        filter.value.emailDomains?.length ||
        filter.value.usageMin !== undefined ||
        filter.value.usageMax !== undefined ||
        filter.value.daysRemainingMin !== undefined ||
        filter.value.daysRemainingMax !== undefined ||
        filter.value.bannedOnly
    )
)

function text(zh, en) {
    return isEn.value ? en : zh
}

function updateFilter(patch) {
    accountsStore.setFilter({ ...accountsStore.filter, ...patch })
}

function toggleArrayFilter(key, value) {
    const current = filter.value[key] ?? []
    const next = current.includes(value)
        ? current.filter((item) => item !== value)
        : [...current, value]
    updateFilter({ [key]: next.length ? next : undefined })
}

function setRangeFilter(key, value, percent = false) {
    updateFilter({
        [key]:
            value === null || value === ''
                ? undefined
                : percent
                  ? Number(value) / 100
                  : Number(value)
    })
}

function clearFilters() {
    accountsStore.clearFilter()
}
</script>

<template>
    <UiCard density="compact" data-testid="account-filter">
        <div class="account-filter-content">
            <div v-if="hasActiveFilters" class="kam-actions account-filter-clear">
                <UiButton
                    variant="ghost"
                    size="sm"
                    data-testid="filter-clear"
                    @click="clearFilters"
                    >{{ text('清除筛选', 'Clear') }}</UiButton
                >
            </div>
            <section class="account-filter-section">
                <span class="kam-muted account-filter-label">{{ text('订阅', 'Plan') }}</span>
                <div class="kam-actions">
                    <UiButton
                        v-for="option in subscriptionOptions"
                        :key="option.value"
                        :variant="
                            filter.subscriptionTypes?.includes(option.value) ? 'secondary' : 'ghost'
                        "
                        size="sm"
                        :aria-pressed="Boolean(filter.subscriptionTypes?.includes(option.value))"
                        :data-testid="`filter-subscription-${option.value}`"
                        @click="toggleArrayFilter('subscriptionTypes', option.value)"
                    >
                        {{ option.label }}
                        <UiBadge dense>{{ stats.bySubscription[option.value] }}</UiBadge>
                    </UiButton>
                </div>
            </section>
            <section class="account-filter-section">
                <span class="kam-muted account-filter-label">{{ text('状态', 'Status') }}</span>
                <div class="kam-actions">
                    <UiButton
                        v-for="option in statusOptions"
                        :key="option.value"
                        :variant="filter.statuses?.includes(option.value) ? 'secondary' : 'ghost'"
                        size="sm"
                        :aria-pressed="Boolean(filter.statuses?.includes(option.value))"
                        :data-testid="`filter-status-${option.value}`"
                        @click="toggleArrayFilter('statuses', option.value)"
                    >
                        {{ text(option.zh, option.en) }}
                        <UiBadge dense>{{ stats.byStatus[option.value] }}</UiBadge>
                    </UiButton>
                    <UiButton
                        :variant="filter.bannedOnly ? 'secondary' : 'ghost'"
                        size="sm"
                        :aria-pressed="Boolean(filter.bannedOnly)"
                        data-testid="filter-banned"
                        @click="updateFilter({ bannedOnly: !filter.bannedOnly })"
                    >
                        {{ text('已封禁', 'Banned') }}
                        <UiBadge dense>{{ stats.bannedCount }}</UiBadge>
                    </UiButton>
                </div>
            </section>
            <section class="account-filter-section">
                <span class="kam-muted account-filter-label">IDP</span>
                <div class="kam-actions">
                    <UiButton
                        v-for="option in idpOptions"
                        :key="option.value"
                        :variant="filter.idps?.includes(option.value) ? 'secondary' : 'ghost'"
                        size="sm"
                        :aria-pressed="Boolean(filter.idps?.includes(option.value))"
                        :data-testid="`filter-idp-${option.value}`"
                        @click="toggleArrayFilter('idps', option.value)"
                    >
                        {{ option.label }} <UiBadge dense>{{ stats.byIdp[option.value] }}</UiBadge>
                    </UiButton>
                </div>
            </section>
            <section v-if="tags.size" class="account-filter-section">
                <span class="kam-muted account-filter-label">{{ text('标签', 'Tags') }}</span>
                <div class="kam-actions">
                    <UiButton
                        v-for="tag in tags.values()"
                        :key="tag.id"
                        :variant="filter.tagIds?.includes(tag.id) ? 'secondary' : 'ghost'"
                        size="sm"
                        :aria-pressed="Boolean(filter.tagIds?.includes(tag.id))"
                        :data-testid="`filter-tag-${tag.id}`"
                        @click="toggleArrayFilter('tagIds', tag.id)"
                    >
                        <UiBadge dense :color="toRgba(tag.color)">{{ tag.name }}</UiBadge>
                    </UiButton>
                </div>
            </section>
            <div class="account-filter-ranges">
                <UiField :label="text('使用量范围 (%)', 'Usage range (%)')">
                    <div class="account-filter-range">
                        <UiInput
                            type="number"
                            min="0"
                            max="100"
                            :model-value="
                                filter.usageMin === undefined ? null : filter.usageMin * 100
                            "
                            :aria-label="text('最低使用量', 'Minimum usage')"
                            placeholder="min"
                            data-testid="filter-usage-min"
                            @update:model-value="setRangeFilter('usageMin', $event, true)"
                        />
                        <span class="kam-muted">–</span>
                        <UiInput
                            type="number"
                            min="0"
                            max="100"
                            :model-value="
                                filter.usageMax === undefined ? null : filter.usageMax * 100
                            "
                            :aria-label="text('最高使用量', 'Maximum usage')"
                            placeholder="max"
                            data-testid="filter-usage-max"
                            @update:model-value="setRangeFilter('usageMax', $event, true)"
                        />
                    </div>
                </UiField>
                <UiField :label="text('剩余天数范围', 'Remaining days range')">
                    <div class="account-filter-range">
                        <UiInput
                            type="number"
                            min="0"
                            :model-value="filter.daysRemainingMin ?? null"
                            :aria-label="text('最少剩余天数', 'Minimum days')"
                            placeholder="min"
                            data-testid="filter-days-min"
                            @update:model-value="setRangeFilter('daysRemainingMin', $event)"
                        />
                        <span class="kam-muted">–</span>
                        <UiInput
                            type="number"
                            min="0"
                            :model-value="filter.daysRemainingMax ?? null"
                            :aria-label="text('最多剩余天数', 'Maximum days')"
                            placeholder="max"
                            data-testid="filter-days-max"
                            @update:model-value="setRangeFilter('daysRemainingMax', $event)"
                        />
                    </div>
                </UiField>
            </div>
            <section v-if="domainCounts.length" class="account-filter-section">
                <span class="kam-muted account-filter-label">{{ text('域名', 'Domain') }}</span>
                <div class="kam-actions">
                    <UiButton
                        v-for="[domain, count] in visibleDomains"
                        :key="domain"
                        :variant="filter.emailDomains?.includes(domain) ? 'secondary' : 'ghost'"
                        size="sm"
                        :aria-pressed="Boolean(filter.emailDomains?.includes(domain))"
                        :data-testid="`filter-domain-${domain}`"
                        @click="toggleArrayFilter('emailDomains', domain)"
                    >
                        @{{ domain }} <UiBadge dense>{{ count }}</UiBadge>
                    </UiButton>
                    <UiButton
                        v-if="domainCounts.length > DOMAIN_DISPLAY_LIMIT"
                        variant="ghost"
                        size="sm"
                        data-testid="filter-domains-expand"
                        @click="showAllDomains = !showAllDomains"
                    >
                        {{
                            showAllDomains
                                ? text('收起', 'Less')
                                : `+${domainCounts.length - DOMAIN_DISPLAY_LIMIT}`
                        }}
                    </UiButton>
                </div>
            </section>
        </div>
    </UiCard>
</template>

<style scoped>
.account-filter-content {
    display: flex;
    flex-direction: column;
    gap: 12px;
}
.account-filter-clear {
    justify-content: flex-end;
}
.account-filter-section {
    display: flex;
    align-items: flex-start;
    gap: 12px;
}
.account-filter-label {
    min-width: 48px;
    padding-top: 5px;
    font-size: 12px;
}
.account-filter-ranges {
    display: flex;
    flex-wrap: wrap;
    gap: 12px 24px;
}
.account-filter-range {
    display: flex;
    align-items: center;
    gap: 8px;
}
.account-filter-range :deep(.ui-input) {
    width: 76px;
}
@media (max-width: 600px) {
    .account-filter-section {
        flex-direction: column;
        gap: 4px;
    }
}
</style>

// Kiro-account-manager/src/renderer/src/components/accounts/AccountFilter.tsx
import { useMemo, useState } from 'react'
import { Button } from '../ui'
import { useAccountsStore } from '@/store/accounts'
import { useTranslation } from '@/hooks/useTranslation'
import type { AccountFilter as FilterType, SubscriptionType, AccountStatus, IdpType } from '@shared/types/account'
import { cn } from '@/lib/utils'

const SubscriptionOptions: { value: SubscriptionType; label: string; color: string; activeColor: string }[] = [
  { value: 'Free', label: 'KIRO FREE', color: 'text-gray-500 border-gray-300', activeColor: 'bg-gray-500 text-white border-gray-500' },
  { value: 'Pro', label: 'KIRO PRO', color: 'text-blue-500 border-blue-300', activeColor: 'bg-blue-500 text-white border-blue-500' },
  { value: 'Pro_Plus', label: 'KIRO PRO+', color: 'text-purple-500 border-purple-300', activeColor: 'bg-purple-500 text-white border-purple-500' },
  { value: 'Enterprise', label: 'KIRO POWER', color: 'text-amber-500 border-amber-300', activeColor: 'bg-amber-500 text-white border-amber-500' }
]

const StatusOptionsZh: { value: AccountStatus; label: string }[] = [
  { value: 'active', label: '正常' },
  { value: 'expired', label: '已过期' },
  { value: 'error', label: '错误' },
  { value: 'unknown', label: '未知' }
]

const StatusOptionsEn: { value: AccountStatus; label: string }[] = [
  { value: 'active', label: 'Active' },
  { value: 'expired', label: 'Expired' },
  { value: 'error', label: 'Error' },
  { value: 'unknown', label: 'Unknown' }
]

const IdpOptions: { value: IdpType; label: string }[] = [
  { value: 'Google', label: 'Google' },
  { value: 'Github', label: 'GitHub' },
  { value: 'BuilderId', label: 'BuilderId' },
  { value: 'Enterprise', label: 'Enterprise' },
  { value: 'AWSIdC', label: 'AWSIdC' }
]

// 解析 ARGB 颜色转换为 CSS rgba
function toRgba(argbColor: string): string {
  // 支持格式: #AARRGGBB 或 #RRGGBB
  let alpha = 255
  let rgb = argbColor
  if (argbColor.length === 9 && argbColor.startsWith('#')) {
    alpha = parseInt(argbColor.slice(1, 3), 16)
    rgb = '#' + argbColor.slice(3)
  }
  const hex = rgb.startsWith('#') ? rgb.slice(1) : rgb
  const r = parseInt(hex.slice(0, 2), 16)
  const g = parseInt(hex.slice(2, 4), 16)
  const b = parseInt(hex.slice(4, 6), 16)
  return `rgba(${r}, ${g}, ${b}, ${alpha / 255})`
}

// 域名筛选默认展示的最大数量，超出部分折叠
const DOMAIN_DISPLAY_LIMIT = 16

export function AccountFilterPanel(): React.ReactNode {
  const { filter, setFilter, clearFilter, tags, accounts, getStats } = useAccountsStore()
  const { t } = useTranslation()
  const isEn = t('common.unknown') === 'Unknown'
  const StatusOptions = isEn ? StatusOptionsEn : StatusOptionsZh
  const [showAllDomains, setShowAllDomains] = useState(false)

  const stats = getStats()

  // 从现有账号中提取邮箱域名后缀及数量，按数量降序
  const domainCounts = useMemo(() => {
    const counts = new Map<string, number>()
    for (const account of accounts.values()) {
      const atIndex = account.email.lastIndexOf('@')
      if (atIndex < 0) continue
      const domain = account.email.slice(atIndex + 1).toLowerCase()
      if (!domain) continue
      counts.set(domain, (counts.get(domain) ?? 0) + 1)
    }
    return Array.from(counts.entries()).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
  }, [accounts])

  // 折叠时也要保证已选中的域名可见
  const visibleDomains = useMemo(() => {
    if (showAllDomains || domainCounts.length <= DOMAIN_DISPLAY_LIMIT) return domainCounts
    const top = domainCounts.slice(0, DOMAIN_DISPLAY_LIMIT)
    const selected = new Set(filter.emailDomains ?? [])
    for (const entry of domainCounts.slice(DOMAIN_DISPLAY_LIMIT)) {
      if (selected.has(entry[0])) top.push(entry)
    }
    return top
  }, [domainCounts, showAllDomains, filter.emailDomains])

  const hasActiveFilters = Boolean(
    filter.subscriptionTypes?.length ||
    filter.statuses?.length ||
    filter.idps?.length ||
    filter.groupIds?.length ||
    filter.tagIds?.length ||
    filter.emailDomains?.length ||
    filter.usageMin !== undefined ||
    filter.usageMax !== undefined ||
    filter.daysRemainingMin !== undefined ||
    filter.daysRemainingMax !== undefined ||
    filter.bannedOnly
  )

  const toggleArrayFilter = <T extends string>(
    key: keyof FilterType,
    value: T
  ): void => {
    const current = (filter[key] as T[] | undefined) ?? []
    const newValue = current.includes(value)
      ? current.filter((v) => v !== value)
      : [...current, value]

    setFilter({
      ...filter,
      [key]: newValue.length > 0 ? newValue : undefined
    })
  }

  const setRangeFilter = (
    minKey: keyof FilterType,
    maxKey: keyof FilterType,
    min: number | undefined,
    max: number | undefined
  ): void => {
    setFilter({
      ...filter,
      [minKey]: min,
      [maxKey]: max
    })
  }

  return (
    <div className="p-3 space-y-2">
      {/* 清除筛选按钮 */}
      {hasActiveFilters && (
        <div className="flex justify-end">
          <Button
            variant="ghost"
            size="sm"
            className="h-6 text-xs px-2"
            onClick={() => clearFilter()}
          >
            {isEn ? 'Clear' : '清除筛选'}
          </Button>
        </div>
      )}
      {/* 第一行：订阅类型 + 状态 + 身份提供商 */}
          <div className="flex flex-wrap items-start gap-x-6 gap-y-2">
            {/* 订阅类型 */}
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground shrink-0">{isEn ? 'Plan:' : '订阅:'}</span>
              <div className="flex flex-wrap gap-1">
                {SubscriptionOptions.map((option) => {
                  const isActive = filter.subscriptionTypes?.includes(option.value)
                  const count = stats.bySubscription[option.value]
                  return (
                    <button
                      key={option.value}
                      className={cn(
                        'px-2 py-0.5 text-xs rounded border transition-colors',
                        isActive ? option.activeColor : `hover:bg-muted/50 ${option.color}`
                      )}
                      onClick={() => toggleArrayFilter('subscriptionTypes', option.value)}
                    >
                      {option.label}({count})
                    </button>
                  )
                })}
              </div>
            </div>

            {/* 状态 */}
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground shrink-0">{isEn ? 'Status:' : '状态:'}</span>
              <div className="flex flex-wrap gap-1">
                {StatusOptions.map((option) => {
                  const isActive = filter.statuses?.includes(option.value)
                  const count = stats.byStatus[option.value]
                  return (
                    <button
                      key={option.value}
                      className={cn(
                        'px-2 py-0.5 text-xs rounded border transition-colors',
                        isActive
                          ? 'bg-primary text-primary-foreground border-primary'
                          : 'hover:bg-muted'
                      )}
                      onClick={() => toggleArrayFilter('statuses', option.value)}
                    >
                      {option.label}({count})
                    </button>
                  )
                })}
                {/* 封禁筛选 */}
                <button
                  className={cn(
                    'px-2 py-0.5 text-xs rounded border transition-colors',
                    filter.bannedOnly
                      ? 'bg-red-500 text-white border-red-500'
                      : 'hover:bg-muted text-red-500 border-red-200'
                  )}
                  onClick={() => setFilter({ ...filter, bannedOnly: !filter.bannedOnly })}
                >
                  {isEn ? 'Banned' : '已封禁'}({stats.bannedCount})
                </button>
              </div>
            </div>

            {/* 身份提供商 */}
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted-foreground shrink-0">IDP:</span>
              <div className="flex flex-wrap gap-1">
                {IdpOptions.map((option) => {
                  const isActive = filter.idps?.includes(option.value)
                  const count = stats.byIdp[option.value]
                  return (
                    <button
                      key={option.value}
                      className={cn(
                        'px-2 py-0.5 text-xs rounded border transition-colors',
                        isActive
                          ? 'bg-primary text-primary-foreground border-primary'
                          : 'hover:bg-muted'
                      )}
                      onClick={() => toggleArrayFilter('idps', option.value)}
                    >
                      {option.label}({count})
                    </button>
                  )
                })}
              </div>
            </div>
          </div>

          {/* 第二行：标签 + 范围筛选（分组改用顶部 Tab 互斥切换，不再多选筛选） */}
          <div className="flex flex-wrap items-start gap-x-6 gap-y-2 mt-2">
            {/* 标签 */}
            {tags.size > 0 && (
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground shrink-0">{isEn ? 'Tags:' : '标签:'}</span>
                <div className="flex flex-wrap gap-1">
                  {Array.from(tags.values()).map((tag) => {
                    const isActive = filter.tagIds?.includes(tag.id)
                    return (
                      <button
                        key={tag.id}
                        className={cn(
                          'px-2 py-0.5 text-xs rounded border transition-colors',
                          isActive ? 'text-white border-transparent' : 'hover:bg-muted'
                        )}
                        style={isActive ? { backgroundColor: toRgba(tag.color) } : undefined}
                        onClick={() => toggleArrayFilter('tagIds', tag.id)}
                      >
                        {tag.name}
                      </button>
                    )
                  })}
                </div>
              </div>
            )}

            {/* 使用量范围 */}
            <div className="flex items-center gap-1">
              <span className="text-xs text-muted-foreground">{isEn ? 'Usage:' : '使用量:'}</span>
              <input
                type="number"
                min="0"
                max="100"
                placeholder="min"
                className="w-14 px-1.5 py-0.5 text-xs rounded-md border border-[var(--glass-border)] bg-[var(--glass-bg-subtle)] backdrop-blur-md focus:outline-none focus:ring-2 focus:ring-primary/40"
                value={filter.usageMin ?? ''}
                onChange={(e) =>
                  setRangeFilter(
                    'usageMin',
                    'usageMax',
                    e.target.value ? Number(e.target.value) / 100 : undefined,
                    filter.usageMax
                  )
                }
              />
              <span className="text-muted-foreground text-xs">-</span>
              <input
                type="number"
                min="0"
                max="100"
                placeholder="max"
                className="w-14 px-1.5 py-0.5 text-xs rounded-md border border-[var(--glass-border)] bg-[var(--glass-bg-subtle)] backdrop-blur-md focus:outline-none focus:ring-2 focus:ring-primary/40"
                value={filter.usageMax !== undefined ? filter.usageMax * 100 : ''}
                onChange={(e) =>
                  setRangeFilter(
                    'usageMin',
                    'usageMax',
                    filter.usageMin,
                    e.target.value ? Number(e.target.value) / 100 : undefined
                  )
                }
              />
              <span className="text-xs text-muted-foreground">%</span>
            </div>

            {/* 剩余天数范围 */}
            <div className="flex items-center gap-1">
              <span className="text-xs text-muted-foreground">{isEn ? 'Days:' : '剩余:'}</span>
              <input
                type="number"
                min="0"
                placeholder="min"
                className="w-14 px-1.5 py-0.5 text-xs rounded-md border border-[var(--glass-border)] bg-[var(--glass-bg-subtle)] backdrop-blur-md focus:outline-none focus:ring-2 focus:ring-primary/40"
                value={filter.daysRemainingMin ?? ''}
                onChange={(e) =>
                  setRangeFilter(
                    'daysRemainingMin',
                    'daysRemainingMax',
                    e.target.value ? Number(e.target.value) : undefined,
                    filter.daysRemainingMax
                  )
                }
              />
              <span className="text-muted-foreground text-xs">-</span>
              <input
                type="number"
                min="0"
                placeholder="max"
                className="w-14 px-1.5 py-0.5 text-xs rounded-md border border-[var(--glass-border)] bg-[var(--glass-bg-subtle)] backdrop-blur-md focus:outline-none focus:ring-2 focus:ring-primary/40"
                value={filter.daysRemainingMax ?? ''}
                onChange={(e) =>
                  setRangeFilter(
                    'daysRemainingMin',
                    'daysRemainingMax',
                    filter.daysRemainingMin,
                    e.target.value ? Number(e.target.value) : undefined
                  )
                }
              />
              <span className="text-xs text-muted-foreground">{isEn ? 'd' : '天'}</span>
            </div>
          </div>

          {/* 第三行：邮箱域名后缀 */}
          {domainCounts.length > 0 && (
            <div className="flex items-start gap-2 mt-2">
              <span className="text-xs text-muted-foreground shrink-0 mt-0.5">{isEn ? 'Domain:' : '域名:'}</span>
              <div className="flex flex-wrap gap-1">
                {visibleDomains.map(([domain, count]) => {
                  const isActive = filter.emailDomains?.includes(domain)
                  return (
                    <button
                      key={domain}
                      className={cn(
                        'px-2 py-0.5 text-xs rounded border transition-colors',
                        isActive
                          ? 'bg-primary text-primary-foreground border-primary'
                          : 'hover:bg-muted'
                      )}
                      onClick={() => toggleArrayFilter('emailDomains', domain)}
                    >
                      @{domain}({count})
                    </button>
                  )
                })}
                {domainCounts.length > DOMAIN_DISPLAY_LIMIT && (
                  <button
                    className="px-2 py-0.5 text-xs rounded border hover:bg-muted text-muted-foreground transition-colors"
                    onClick={() => setShowAllDomains(!showAllDomains)}
                  >
                    {showAllDomains
                      ? (isEn ? 'Less' : '收起')
                      : `+${domainCounts.length - DOMAIN_DISPLAY_LIMIT}`}
                  </button>
                )}
              </div>
            </div>
          )}
    </div>
  )
}
