// Kiro-account-manager/src/renderer-vue/src/components/accounts/GroupManageDialog.vue
<script setup>
import { computed, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { UiBadge, UiButton, UiCard, UiDialog, UiField, UiInput, confirmDialog } from '@lingyzh/ui'
import { Edit2, FolderOpen, Plus, Trash2, Users, X } from 'lucide-vue-next'
import { useAccountsStore } from '../../stores/accounts'
import { useTranslation } from '../../composables/useTranslation'

const props = defineProps({ open: { type: Boolean, required: true } })
const emit = defineEmits(['update:open'])
const accountsStore = useAccountsStore()
const { accounts, groups } = storeToRefs(accountsStore)
const { actualLanguage } = useTranslation()
const isEn = computed(() => actualLanguage.value === 'en')
const groupList = computed(() => [...groups.value.values()].sort((a, b) => a.order - b.order))
const ungroupedCount = computed(
    () => [...accounts.value.values()].filter((account) => !account.groupId).length
)

const editingId = ref(null)
const editName = ref('')
const editDescription = ref('')
const editColor = ref('#3b82f6')
const isCreating = ref(false)
const newName = ref('')
const newDescription = ref('')
const newColor = ref('#3b82f6')
const assigningGroupId = ref(null)
const confirmingDelete = ref(false)

function text(zh, en) {
    return isEn.value ? en : zh
}

function closeDialog() {
    emit('update:open', false)
}

function groupAccounts(groupId) {
    return [...accounts.value.values()].filter((account) => account.groupId === groupId)
}

function assignableAccounts(groupId) {
    return [...accounts.value.values()].filter((account) => account.groupId !== groupId)
}

function createGroup() {
    if (!newName.value.trim()) return
    accountsStore.addGroup({
        name: newName.value.trim(),
        description: newDescription.value.trim() || undefined,
        color: newColor.value
    })
    newName.value = ''
    newDescription.value = ''
    newColor.value = '#3b82f6'
    isCreating.value = false
}

function startEdit(group) {
    editingId.value = group.id
    editName.value = group.name
    editDescription.value = group.description || ''
    editColor.value = group.color || '#3b82f6'
}

function saveEdit() {
    if (!editingId.value || !editName.value.trim()) return
    accountsStore.updateGroup(editingId.value, {
        name: editName.value.trim(),
        description: editDescription.value.trim() || undefined,
        color: editColor.value
    })
    editingId.value = null
}

async function deleteGroup(group) {
    if (confirmingDelete.value) return
    confirmingDelete.value = true
    try {
        const count = groupAccounts(group.id).length
        const message =
            count > 0
                ? text(
                      `确定要删除分组「${group.name}」吗？\n该分组包含 ${count} 个账号，删除后这些账号将变为未分组状态。`,
                      `Delete group “${group.name}”?\nIts ${count} accounts will become ungrouped.`
                  )
                : text(`确定要删除分组「${group.name}」吗？`, `Delete group “${group.name}”?`)
        const confirmed = await confirmDialog({
            title: text('删除分组', 'Delete group'),
            message,
            confirmText: text('删除', 'Delete'),
            tone: 'danger'
        })
        if (confirmed && props.open) accountsStore.removeGroup(group.id)
    } finally {
        confirmingDelete.value = false
    }
}

function assignAccount(groupId, accountId) {
    accountsStore.moveAccountsToGroup([accountId], groupId)
}
</script>

<template>
    <UiDialog
        :open="open"
        size="lg"
        scrollable
        :content-label="text('分组管理内容', 'Group management content')"
        @update:open="emit('update:open', $event)"
    >
        <template #header>
            <h2 class="group-dialog-title">
                <FolderOpen :size="18" aria-hidden="true" />{{
                    text('分组管理', 'Group Management')
                }}
            </h2>
        </template>
        <div class="kam-dialog-content" data-testid="group-dialog">
            <p class="kam-muted">
                {{ text(`共 ${groupList.length} 个分组`, `${groupList.length} groups`) }} ·
                {{ text(`${ungroupedCount} 个未分组账号`, `${ungroupedCount} ungrouped`) }}
            </p>

            <UiCard v-if="isCreating" density="compact">
                <div class="kam-dialog-content">
                    <UiField
                        v-slot="{ controlAttrs }"
                        :label="text('分组名称', 'Group name')"
                        for="group-new-name"
                    >
                        <UiInput
                            id="group-new-name"
                            v-model="newName"
                            v-bind="controlAttrs"
                            data-testid="group-new-name"
                        />
                    </UiField>
                    <UiField
                        v-slot="{ controlAttrs }"
                        :label="text('描述（可选）', 'Description (optional)')"
                        for="group-new-description"
                    >
                        <UiInput
                            id="group-new-description"
                            v-model="newDescription"
                            v-bind="controlAttrs"
                            data-testid="group-new-description"
                        />
                    </UiField>
                    <UiField :label="text('颜色', 'Color')" for="group-new-color">
                        <input
                            id="group-new-color"
                            v-model="newColor"
                            type="color"
                            class="account-color-input"
                            data-testid="group-new-color"
                        />
                    </UiField>
                    <div class="kam-actions group-actions">
                        <UiButton
                            variant="ghost"
                            data-testid="group-cancel-create"
                            @click="isCreating = false"
                            >{{ text('取消', 'Cancel') }}</UiButton
                        >
                        <UiButton
                            :disabled="!newName.trim()"
                            data-testid="group-create"
                            @click="createGroup"
                            >{{ text('创建', 'Create') }}</UiButton
                        >
                    </div>
                </div>
            </UiCard>
            <UiButton v-else variant="secondary" data-testid="group-new" @click="isCreating = true">
                <Plus :size="16" aria-hidden="true" />{{ text('新建分组', 'New Group') }}
            </UiButton>

            <div class="group-list">
                <UiCard
                    v-for="group in groupList"
                    :key="group.id"
                    density="compact"
                    :data-testid="`group-row-${group.id}`"
                >
                    <div v-if="editingId === group.id" class="kam-dialog-content">
                        <UiField
                            v-slot="{ controlAttrs }"
                            :label="text('分组名称', 'Group name')"
                            :for="`group-name-${group.id}`"
                        >
                            <UiInput
                                :id="`group-name-${group.id}`"
                                v-model="editName"
                                v-bind="controlAttrs"
                                data-testid="group-edit-name"
                            />
                        </UiField>
                        <UiField
                            v-slot="{ controlAttrs }"
                            :label="text('描述（可选）', 'Description (optional)')"
                            :for="`group-description-${group.id}`"
                        >
                            <UiInput
                                :id="`group-description-${group.id}`"
                                v-model="editDescription"
                                v-bind="controlAttrs"
                                data-testid="group-edit-description"
                            />
                        </UiField>
                        <UiField :label="text('颜色', 'Color')" :for="`group-color-${group.id}`">
                            <input
                                :id="`group-color-${group.id}`"
                                v-model="editColor"
                                type="color"
                                class="account-color-input"
                                data-testid="group-edit-color"
                            />
                        </UiField>
                        <div class="kam-actions group-actions">
                            <UiButton
                                variant="ghost"
                                data-testid="group-cancel-edit"
                                @click="editingId = null"
                                >{{ text('取消', 'Cancel') }}</UiButton
                            >
                            <UiButton
                                :disabled="!editName.trim()"
                                data-testid="group-save"
                                @click="saveEdit"
                                >{{ text('保存', 'Save') }}</UiButton
                            >
                        </div>
                    </div>
                    <div v-else-if="assigningGroupId === group.id" class="kam-dialog-content">
                        <div class="group-heading">
                            <span
                                class="group-color"
                                :style="{ backgroundColor: group.color || '#3b82f6' }"
                            />{{ group.name }}
                        </div>
                        <div v-if="groupAccounts(group.id).length">
                            <p class="kam-muted">
                                {{ text('当前分组内的账号：', 'Accounts in this group:') }}
                            </p>
                            <div class="kam-actions">
                                <UiButton
                                    v-for="account in groupAccounts(group.id)"
                                    :key="account.id"
                                    variant="ghost"
                                    size="sm"
                                    :data-testid="`group-remove-account-${account.id}`"
                                    @click="assignAccount(undefined, account.id)"
                                >
                                    {{ account.email }}<X :size="13" aria-hidden="true" />
                                </UiButton>
                            </div>
                        </div>
                        <div v-if="assignableAccounts(group.id).length">
                            <p class="kam-muted">
                                {{ text('点击添加到此分组：', 'Click to add to this group:') }}
                            </p>
                            <div class="kam-actions group-account-list">
                                <UiButton
                                    v-for="account in assignableAccounts(group.id)"
                                    :key="account.id"
                                    variant="ghost"
                                    size="sm"
                                    :data-testid="`group-add-account-${account.id}`"
                                    @click="assignAccount(group.id, account.id)"
                                    >{{ account.email }}</UiButton
                                >
                            </div>
                        </div>
                        <div class="kam-actions group-actions">
                            <UiButton
                                variant="secondary"
                                data-testid="group-finish-assign"
                                @click="assigningGroupId = null"
                                >{{ text('完成', 'Done') }}</UiButton
                            >
                        </div>
                    </div>
                    <div v-else class="group-row">
                        <span
                            class="group-color"
                            :style="{ backgroundColor: group.color || '#3b82f6' }"
                        />
                        <div class="group-main">
                            <strong>{{ group.name }}</strong>
                            <p v-if="group.description" class="kam-muted">
                                {{ group.description }}
                            </p>
                        </div>
                        <UiBadge dense>{{ groupAccounts(group.id).length }}</UiBadge>
                        <UiButton
                            variant="ghost"
                            size="sm"
                            :aria-label="text('管理账号', 'Manage accounts')"
                            :data-testid="`group-assign-${group.id}`"
                            @click="assigningGroupId = group.id"
                            ><Users :size="16" aria-hidden="true"
                        /></UiButton>
                        <UiButton
                            variant="ghost"
                            size="sm"
                            :aria-label="text('编辑', 'Edit')"
                            :data-testid="`group-edit-${group.id}`"
                            @click="startEdit(group)"
                            ><Edit2 :size="16" aria-hidden="true"
                        /></UiButton>
                        <UiButton
                            variant="ghost"
                            size="sm"
                            :aria-label="text('删除', 'Delete')"
                            :disabled="confirmingDelete"
                            :data-testid="`group-delete-${group.id}`"
                            @click="deleteGroup(group)"
                            ><Trash2 :size="16" aria-hidden="true"
                        /></UiButton>
                    </div>
                </UiCard>
                <p v-if="!groupList.length && !isCreating" class="kam-muted">
                    {{
                        text(
                            '暂无分组，点击上方按钮创建第一个分组',
                            'No groups. Create your first group above.'
                        )
                    }}
                </p>
            </div>
        </div>
        <template #footer
            ><UiButton variant="secondary" data-testid="group-close" @click="closeDialog">{{
                text('关闭', 'Close')
            }}</UiButton></template
        >
    </UiDialog>
</template>

<style scoped>
.kam-dialog-content :deep(.ui-field) {
    flex-direction: column;
    align-items: stretch;
    gap: 6px;
    padding: 0;
    border: 0;
}
.kam-dialog-content :deep(.ui-input) {
    width: 100%;
}
.group-dialog-title {
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 0;
    font-size: 16px;
}
.group-list {
    display: flex;
    flex-direction: column;
    gap: 8px;
}
.group-row {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 8px;
    min-width: 0;
}
.group-main {
    flex: 1;
    min-width: 120px;
}
.group-main p {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
.group-color {
    width: 16px;
    height: 16px;
    border-radius: 4px;
    flex: none;
    border: 1px solid var(--border);
}
.group-heading {
    display: flex;
    align-items: center;
    gap: 8px;
    font-weight: 600;
}
.group-actions {
    justify-content: flex-end;
}
.group-account-list {
    max-height: 128px;
    overflow: auto;
}
.account-color-input {
    display: block;
    width: 44px;
    height: 36px;
    padding: 2px;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: transparent;
}
</style>

// Kiro-account-manager/src/renderer/src/components/accounts/GroupManageDialog.tsx
import { useState } from 'react'
import { Button, Card, CardContent, CardHeader, CardTitle } from '../ui'
import { useAccountsStore } from '@/store/accounts'
import { useTranslation } from '@/hooks/useTranslation'
import type { AccountGroup } from '@shared/types/account'
import { X, Plus, Edit2, Trash2, Users, Check, FolderOpen } from 'lucide-react'

interface GroupManageDialogProps {
  isOpen: boolean
  onClose: () => void
}

export function GroupManageDialog({ isOpen, onClose }: GroupManageDialogProps): React.ReactNode {
  const { groups, accounts, addGroup, updateGroup, removeGroup, moveAccountsToGroup } = useAccountsStore()
  const { t } = useTranslation()
  const isEn = t('common.unknown') === 'Unknown'

  // 编辑状态
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editName, setEditName] = useState('')
  const [editDescription, setEditDescription] = useState('')
  const [editColor, setEditColor] = useState('#3b82f6')

  // 新建状态
  const [isCreating, setIsCreating] = useState(false)
  const [newName, setNewName] = useState('')
  const [newDescription, setNewDescription] = useState('')
  const [newColor, setNewColor] = useState('#3b82f6')

  // 分配账号状态
  const [assigningGroupId, setAssigningGroupId] = useState<string | null>(null)

  // 获取分组内的账号数量
  const getGroupAccountCount = (groupId: string): number => {
    return Array.from(accounts.values()).filter(acc => acc.groupId === groupId).length
  }

  // 获取未分组的账号数量
  const getUngroupedCount = (): number => {
    return Array.from(accounts.values()).filter(acc => !acc.groupId).length
  }

  // 创建分组
  const handleCreate = () => {
    if (!newName.trim()) return
    addGroup({
      name: newName.trim(),
      description: newDescription.trim() || undefined,
      color: newColor
    })
    setNewName('')
    setNewDescription('')
    setNewColor('#3b82f6')
    setIsCreating(false)
  }

  // 开始编辑
  const handleStartEdit = (group: AccountGroup) => {
    setEditingId(group.id)
    setEditName(group.name)
    setEditDescription(group.description || '')
    setEditColor(group.color || '#3b82f6')
  }

  // 保存编辑
  const handleSaveEdit = () => {
    if (!editingId || !editName.trim()) return
    updateGroup(editingId, {
      name: editName.trim(),
      description: editDescription.trim() || undefined,
      color: editColor
    })
    setEditingId(null)
  }

  // 删除分组
  const handleDelete = (id: string, name: string) => {
    const count = getGroupAccountCount(id)
    const msg = count > 0
      ? `确定要删除分组「${name}」吗？\n该分组包含 ${count} 个账号，删除后这些账号将变为未分组状态。`
      : `确定要删除分组「${name}」吗？`
    if (confirm(msg)) {
      removeGroup(id)
    }
  }

  // 批量分配账号到分组（不退出分配模式，允许连续操作）
  const handleAssignAccounts = (groupId: string | undefined, accountIds: string[]) => {
    moveAccountsToGroup(accountIds, groupId)
  }

  // 获取可分配的账号列表
  const getAssignableAccounts = (groupId: string) => {
    return Array.from(accounts.values()).filter(acc => acc.groupId !== groupId)
  }

  // 获取分组内的账号列表
  const getGroupAccounts = (groupId: string) => {
    return Array.from(accounts.values()).filter(acc => acc.groupId === groupId)
  }

  const groupList = Array.from(groups.values()).sort((a, b) => a.order - b.order)

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />

      <Card className="relative w-full max-w-2xl max-h-[85vh] overflow-hidden z-10 flex flex-col">
        <CardHeader className="flex flex-row items-center justify-between pb-2 shrink-0">
          <CardTitle className="flex items-center gap-2">
            <FolderOpen className="h-5 w-5" />
            {isEn ? 'Group Management' : '分组管理'}
          </CardTitle>
          <Button variant="ghost" size="icon" onClick={onClose} className="rounded-lg hover:bg-red-500 hover:text-white transition-colors">
            <X className="h-4 w-4" />
          </Button>
        </CardHeader>

        <CardContent className="flex-1 overflow-auto space-y-4">
          {/* 统计信息 */}
          <div className="flex gap-4 text-sm text-muted-foreground">
            <span>{isEn ? `${groupList.length} groups` : `共 ${groupList.length} 个分组`}</span>
            <span>•</span>
            <span>{isEn ? `${getUngroupedCount()} ungrouped` : `${getUngroupedCount()} 个未分组账号`}</span>
          </div>

          {/* 新建分组 */}
          {isCreating ? (
            <div className="p-4 border rounded-lg space-y-3 bg-muted/30">
              <div className="flex items-center gap-2">
                <input
                  type="color"
                  value={newColor}
                  onChange={(e) => setNewColor(e.target.value)}
                  className="w-8 h-8 rounded cursor-pointer"
                />
                <input
                  type="text"
                  placeholder={isEn ? 'Group name' : '分组名称'}
                  value={newName}
                  onChange={(e) => setNewName(e.target.value)}
                  className="flex-1 px-3 py-2 border rounded-lg text-sm"
                  autoFocus
                />
              </div>
              <input
                type="text"
                placeholder={isEn ? 'Description (optional)' : '分组描述（可选）'}
                value={newDescription}
                onChange={(e) => setNewDescription(e.target.value)}
                className="w-full px-3 py-2 border rounded-lg text-sm"
              />
              <div className="flex justify-end gap-2">
                <Button variant="outline" size="sm" onClick={() => setIsCreating(false)}>
                  {isEn ? 'Cancel' : '取消'}
                </Button>
                <Button size="sm" onClick={handleCreate} disabled={!newName.trim()}>
                  <Check className="h-4 w-4 mr-1" />
                  {isEn ? 'Create' : '创建'}
                </Button>
              </div>
            </div>
          ) : (
            <Button variant="outline" className="w-full" onClick={() => setIsCreating(true)}>
              <Plus className="h-4 w-4 mr-2" />
              {isEn ? 'New Group' : '新建分组'}
            </Button>
          )}

          {/* 分组列表 */}
          <div className="space-y-2">
            {groupList.map((group) => (
              <div
                key={group.id}
                className="p-3 border rounded-lg hover:bg-muted/30 transition-colors"
              >
                {editingId === group.id ? (
                  // 编辑模式
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <input
                        type="color"
                        value={editColor}
                        onChange={(e) => setEditColor(e.target.value)}
                        className="w-8 h-8 rounded cursor-pointer"
                      />
                      <input
                        type="text"
                        value={editName}
                        onChange={(e) => setEditName(e.target.value)}
                        className="flex-1 px-3 py-1.5 border rounded text-sm"
                        autoFocus
                      />
                    </div>
                    <input
                      type="text"
                      placeholder={isEn ? 'Description' : '分组描述'}
                      value={editDescription}
                      onChange={(e) => setEditDescription(e.target.value)}
                      className="w-full px-3 py-1.5 border rounded text-sm"
                    />
                    <div className="flex justify-end gap-2">
                      <Button variant="outline" size="sm" onClick={() => setEditingId(null)}>
                        {isEn ? 'Cancel' : '取消'}
                      </Button>
                      <Button size="sm" onClick={handleSaveEdit}>
                        {isEn ? 'Save' : '保存'}
                      </Button>
                    </div>
                  </div>
                ) : assigningGroupId === group.id ? (
                  // 分配账号模式
                  <div className="space-y-3">
                    <div className="flex items-center gap-2">
                      <div
                        className="w-4 h-4 rounded"
                        style={{ backgroundColor: group.color || '#3b82f6' }}
                      />
                      <span className="font-medium">{group.name}</span>
                      <span className="text-sm text-muted-foreground">- 选择要添加的账号</span>
                    </div>
                    
                    {/* 当前分组内的账号 */}
                    {getGroupAccounts(group.id).length > 0 && (
                      <div className="space-y-1">
                        <p className="text-xs text-muted-foreground">{isEn ? 'Accounts in this group:' : '当前分组内的账号：'}</p>
                        <div className="flex flex-wrap gap-1">
                          {getGroupAccounts(group.id).map(acc => (
                            <span
                              key={acc.id}
                              className="inline-flex items-center gap-1 px-2 py-0.5 bg-primary/10 text-primary rounded text-xs"
                            >
                              {acc.email}
                              <button
                                onClick={() => handleAssignAccounts(undefined, [acc.id])}
                                className="hover:text-destructive"
                                title={isEn ? 'Remove from group' : '移出分组'}
                              >
                                <X className="h-3 w-3" />
                              </button>
                            </span>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* 可添加的账号 */}
                    {getAssignableAccounts(group.id).length > 0 && (
                      <div className="space-y-1">
                        <p className="text-xs text-muted-foreground">{isEn ? 'Click to add to this group:' : '点击添加到此分组：'}</p>
                        <div className="flex flex-wrap gap-1 max-h-32 overflow-auto">
                          {getAssignableAccounts(group.id).map(acc => (
                            <button
                              key={acc.id}
                              onClick={() => handleAssignAccounts(group.id, [acc.id])}
                              className="px-2 py-0.5 bg-muted hover:bg-primary/20 rounded text-xs transition-colors"
                            >
                              {acc.email}
                            </button>
                          ))}
                        </div>
                      </div>
                    )}

                    <div className="flex justify-end">
                      <Button variant="outline" size="sm" onClick={() => setAssigningGroupId(null)}>
                        完成
                      </Button>
                    </div>
                  </div>
                ) : (
                  // 显示模式
                  <div className="flex items-center gap-3">
                    <div
                      className="w-4 h-4 rounded shrink-0"
                      style={{ backgroundColor: group.color || '#3b82f6' }}
                    />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="font-medium truncate">{group.name}</span>
                        <span className="text-xs text-muted-foreground flex items-center gap-1">
                          <Users className="h-3 w-3" />
                          {getGroupAccountCount(group.id)}
                        </span>
                      </div>
                      {group.description && (
                        <p className="text-xs text-muted-foreground truncate">{group.description}</p>
                      )}
                    </div>
                    <div className="flex items-center gap-1 shrink-0">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8"
                        onClick={() => setAssigningGroupId(group.id)}
                        title={isEn ? 'Manage accounts' : '管理账号'}
                      >
                        <Users className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8"
                        onClick={() => handleStartEdit(group)}
                        title={isEn ? 'Edit' : '编辑'}
                      >
                        <Edit2 className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 text-destructive hover:text-destructive"
                        onClick={() => handleDelete(group.id, group.name)}
                        title={isEn ? 'Delete' : '删除'}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            ))}

            {groupList.length === 0 && !isCreating && (
              <div className="text-center py-8 text-muted-foreground">
                <FolderOpen className="h-12 w-12 mx-auto mb-2 opacity-50" />
                <p>{isEn ? 'No groups' : '暂无分组'}</p>
                <p className="text-sm">{isEn ? 'Click the button above to create your first group' : '点击上方按钮创建第一个分组'}</p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
