// Kiro-account-manager/src/renderer-vue/src/components/proxy/ModelIdentityDetails.vue
<script setup>
import { computed, onBeforeUnmount, ref } from 'vue'
import { UiBadge, UiButton } from '@lingyzh/ui'
import { Check, Copy } from 'lucide-vue-next'

const props = defineProps({
    sourceId: { type: String, required: true },
    clientId: { type: String, required: true },
    isEn: { type: Boolean, required: true }
})
const copied = ref('')
const unchanged = computed(() => props.sourceId === props.clientId)
let copyTimer
let active = true

async function copy(value, kind) {
    try {
        await navigator.clipboard.writeText(value)
        if (!active) return
        copied.value = kind
        if (copyTimer) clearTimeout(copyTimer)
        copyTimer = setTimeout(() => {
            if (active && copied.value === kind) copied.value = ''
        }, 2000)
    } catch {
        // The full ID remains selectable when clipboard access is unavailable.
    }
}

onBeforeUnmount(() => {
    active = false
    if (copyTimer) clearTimeout(copyTimer)
})
</script>

<template>
    <div class="kam-model-identity" data-testid="model-identity-details">
        <div class="kam-model-identity-heading">
            <strong>{{ isEn ? 'Model IDs' : '模型 ID' }}</strong
            ><UiBadge v-if="unchanged" tone="neutral">{{ isEn ? 'Unchanged' : '未改写' }}</UiBadge>
        </div>
        <div v-for="kind in ['source', 'client']" :key="kind">
            <small class="kam-muted">{{
                kind === 'source'
                    ? isEn
                        ? 'Upstream source ID'
                        : '上游原始 ID'
                    : isEn
                      ? 'Client model ID'
                      : '客户端模型 ID'
            }}</small>
            <div class="kam-model-identity-row">
                <code class="kam-mono">{{ kind === 'source' ? sourceId : clientId }}</code>
                <UiButton
                    icon
                    size="sm"
                    variant="ghost"
                    :aria-label="`${isEn ? 'Copy' : '复制'} ${kind}`"
                    :data-testid="`model-copy-${kind}`"
                    @click="copy(kind === 'source' ? sourceId : clientId, kind)"
                    ><Check v-if="copied === kind" :size="14" /><Copy v-else :size="14"
                /></UiButton>
            </div>
        </div>
    </div>
</template>

<style scoped>
.kam-model-identity {
    display: flex;
    flex-direction: column;
    gap: 8px;
    min-width: 0;
    padding: 12px;
    border: 1px solid var(--border);
    border-radius: var(--radius-md, 8px);
}
.kam-model-identity-heading,
.kam-model-identity-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
}
.kam-model-identity-row code {
    min-width: 0;
    flex: 1;
    overflow-wrap: anywhere;
    user-select: all;
}
</style>

// Kiro-account-manager/src/renderer/src/components/proxy/ModelIdentityDetails.tsx
import { useState } from 'react'
import { Check, Copy } from 'lucide-react'
import { Badge, Button } from '../ui'

export interface ModelIdentityDetailsProps {
    sourceId: string
    clientId: string
    isEn: boolean
}

export function ModelIdentityDetails({ sourceId, clientId, isEn }: ModelIdentityDetailsProps) {
    const [copied, setCopied] = useState<'source' | 'client' | null>(null)
    const unchanged = sourceId === clientId

    async function copy(value: string, kind: 'source' | 'client') {
        try {
            await navigator.clipboard.writeText(value)
            setCopied(kind)
            window.setTimeout(() => setCopied(current => current === kind ? null : current), 2000)
        } catch {
            // The full ID stays selectable when clipboard access is unavailable.
        }
    }

    return (
        <div className="min-w-0 space-y-2 rounded-xl border border-border bg-background/60 p-3">
            <div className="flex items-center justify-between gap-2">
                <p className="text-xs font-semibold text-foreground">{isEn ? 'Model IDs' : '模型 ID'}</p>
                {unchanged && <Badge variant="secondary" className="shrink-0">{isEn ? 'Unchanged' : '未改写'}</Badge>}
            </div>
            {([
                ['source', sourceId, isEn ? 'Upstream source ID' : '上游原始 ID'],
                ['client', clientId, isEn ? 'Client model ID' : '客户端模型 ID']
            ] as const).map(([kind, value, label]) => (
                <div key={kind} className="min-w-0">
                    <p className="mb-1 text-xs text-muted-foreground">{label}</p>
                    <div className="flex min-w-0 items-start gap-1.5">
                        <code className="min-w-0 flex-1 select-all break-all rounded-lg bg-muted/70 px-2 py-1.5 font-mono text-xs leading-5 text-foreground">
                            {value}
                        </code>
                        <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 shrink-0"
                            aria-label={`${isEn ? 'Copy' : '复制'} ${label}`}
                            title={isEn ? 'Copy ID' : '复制 ID'}
                            onClick={() => { void copy(value, kind) }}
                        >
                            {copied === kind ? <Check className="h-3.5 w-3.5 text-success" /> : <Copy className="h-3.5 w-3.5" />}
                        </Button>
                    </div>
                </div>
            ))}
        </div>
    )
}
