// Kiro-account-manager/src/renderer/src/components/proxy/ClaudeDesktopConfig.tsx
import { useEffect, useRef, useState } from 'react'
import { Loader2, Plus, RotateCcw, Trash2 } from 'lucide-react'
import { Button } from '../ui'
import {
    defaultDesktopRoutes, desktopModelName, desktopClientModelId, DESKTOP_ROLE_IDS,
    type DesktopConfigInput, type DesktopConfigOperation, type DesktopConfigPreview,
    type DesktopModelFamily, type DesktopModelOption
} from '../../../../shared/desktopConfig'

interface Props {
    models: DesktopModelOption[]
    loading: boolean
    isEn: boolean
    busy: boolean
    onBusyChange: (busy: boolean) => void
    onReload: () => void
}

export function ClaudeDesktopConfig({ models, loading, isEn, busy, onBusyChange, onReload }: Props) {
    const [input, setInput] = useState<DesktopConfigInput>(() => defaultDesktopRoutes([]))
    const [ready, setReady] = useState(false)
    const [preview, setPreview] = useState<DesktopConfigPreview | null>(null)
    const [operations, setOperations] = useState<DesktopConfigOperation[]>([])
    const [error, setError] = useState('')
    const [message, setMessage] = useState('')
    const [restoreId, setRestoreId] = useState('')
    const initialized = useRef(false)
    const working = useRef(false)
    const modelKey = models.map(model => model.id).join('\0')

    useEffect(() => {
        let cancelled = false
        window.api.proxyDesktopState().then(result => {
            if (cancelled) return
            if (!result.success) {
                setError(result.error)
                return
            }
            if (result.data.input) {
                initialized.current = true
                setInput(result.data.input)
            }
            setOperations(result.data.operations)
            setReady(true)
        }).catch(error => { if (!cancelled) setError(String(error)) })
        return () => { cancelled = true }
    }, [])

    useEffect(() => {
        setPreview(null)
        if (ready && models.length && !initialized.current) {
            initialized.current = true
            setInput(defaultDesktopRoutes(models))
        }
    }, [ready, modelKey]) // Preserve manual choices when the catalog reloads.

    function change(next: DesktopConfigInput): void {
        initialized.current = true
        setInput(next)
        setPreview(null)
        setError('')
        setMessage('')
    }

    function addRoute(): void {
        let suffix = 2
        while (input.routes.some(route => route.id === `${DESKTOP_ROLE_IDS.sonnet}-kam-${suffix}`)) suffix++
        change({ ...input, routes: [...input.routes, {
            id: `${DESKTOP_ROLE_IDS.sonnet}-kam-${suffix}`, family: 'sonnet',
            label: isEn ? `Model ${suffix}` : `模型 ${suffix}`, modelId: ''
        }] })
    }

    async function refreshOperations(refreshInput = false): Promise<void> {
        const result = await window.api.proxyDesktopState()
        if (!result.success) throw new Error(result.error)
        setOperations(result.data.operations)
        if (refreshInput) setInput(result.data.input || defaultDesktopRoutes(models))
    }

    async function run(action: 'preview' | 'apply' | 'restore'): Promise<void> {
        if (working.current) return
        working.current = true
        onBusyChange(true)
        setError('')
        setMessage('')
        try {
            if (action === 'preview') {
                const result = await window.api.proxyDesktopPreview(input)
                if (!result.success) throw new Error(result.error)
                setPreview(result.data)
            } else if (action === 'apply' && preview) {
                const result = await window.api.proxyDesktopApply(preview.token)
                setPreview(null)
                if (!result.success) throw new Error(result.error)
                setMessage(isEn ? 'Configuration written. Start the KAM proxy, then launch Claude Desktop. Live inference has not been tested.' : '配置已写入。先启动 KAM 反代，再启动 Claude Desktop；尚未验证真实推理请求。')
                await refreshOperations()
            } else if (action === 'restore' && restoreId) {
                const result = await window.api.proxyDesktopRestore(restoreId)
                if (!result.success) throw new Error(result.error)
                setRestoreId('')
                setPreview(null)
                setMessage(isEn ? 'Restored the files to their state before this operation.' : '已恢复到此次操作之前的文件状态。')
                await refreshOperations(true)
            }
        } catch (error) {
            setError(error instanceof Error ? error.message : String(error))
            await refreshOperations().catch(() => {})
        } finally {
            working.current = false
            onBusyChange(false)
        }
    }

    const missingModels = input.routes.some(route => !models.some(model => model.id === route.modelId))
    const recoverable = operations.filter(operation => operation.status !== 'restored')
    const pending = recoverable.some(operation => operation.status === 'pending')
    const controlClass = 'w-full rounded-lg border bg-background px-3 py-2 text-sm min-w-0'

    return <div className="space-y-4">
        <div className="rounded-xl border bg-primary/5 p-4 space-y-2">
            <h3 className="font-semibold">{isEn ? 'Claude Desktop · First-launch gateway setup' : 'Claude Desktop · 首次启动网关配置'}</h3>
            <p className="text-sm text-muted-foreground">{isEn
                ? 'Creates and activates a dedicated KAM 3P profile. Each menu entry maps to the actual target model below; other clients are unaffected.'
                : '创建并选中独立的 KAM 3P 配置。每个菜单条目映射到下方实际目标模型，不影响其他客户端。'}</p>
            <p className="text-xs text-muted-foreground">{isEn
                ? 'Apply before first launch, or fully quit Desktop first. Existing MCP, preferences and other gateway profiles are preserved.'
                : '可在首次启动前配置；已运行时请先完全退出 Desktop。保留已有 MCP、偏好和其他网关配置。'}</p>
        </div>
        <fieldset disabled={busy || !ready} className="space-y-3 min-w-0">
            <div className="flex justify-between items-center gap-2">
                <span className="font-medium text-sm">{isEn ? 'Desktop model menu' : 'Desktop 模型菜单'}</span>
                <Button variant="outline" size="sm" onClick={onReload} disabled={loading || busy}>
                    {loading && <Loader2 className="h-4 w-4 animate-spin" />}{isEn ? 'Reload models' : '刷新模型'}
                </Button>
            </div>
            {input.routes.map((route, index) => <div key={route.id} className="rounded-xl border p-3 space-y-3">
                <div className="flex items-center justify-between gap-3">
                    <label className="flex items-center gap-2 text-sm cursor-pointer">
                        <input type="radio" name="desktop-default-model" checked={input.defaultRouteId === route.id}
                            onChange={() => change({ ...input, defaultRouteId: route.id })} />
                        {input.defaultRouteId === route.id ? (isEn ? 'Default model' : '默认模型') : (isEn ? 'Set as default' : '设为默认')}
                    </label>
                    {index >= 3 && <Button size="sm" variant="ghost" aria-label={isEn ? 'Remove model' : '删除模型'} onClick={() => change({
                        routes: input.routes.filter(item => item.id !== route.id),
                        defaultRouteId: input.defaultRouteId === route.id ? input.routes[0].id : input.defaultRouteId
                    })}><Trash2 className="h-4 w-4" /></Button>}
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-[100px_1fr] gap-3">
                    <label className="space-y-1 text-xs text-muted-foreground">{isEn ? 'Role' : '档位'}
                        <select className={controlClass} value={route.family} disabled={index < 3} onChange={event => {
                            const family = event.target.value as DesktopModelFamily
                            const id = `${DESKTOP_ROLE_IDS[family]}-kam-${crypto.randomUUID().slice(0, 8)}`
                            change({ routes: input.routes.map(item => item.id === route.id ? { ...item, family, id } : item), defaultRouteId: input.defaultRouteId === route.id ? id : input.defaultRouteId })
                        }}>
                            <option value="opus">Opus</option><option value="sonnet">Sonnet</option><option value="haiku">Haiku</option>
                        </select>
                    </label>
                    <label className="space-y-1 text-xs text-muted-foreground">{isEn ? 'Menu label' : '菜单名称'}
                        <input className={controlClass} value={desktopModelName(route.modelId)} readOnly />
                    </label>
                </div>
                <label className="block space-y-1 text-xs text-muted-foreground">{isEn ? 'Actual target model' : '实际调用的模型'}
                    <select className={controlClass} value={route.modelId} onChange={event => change({ ...input, routes: input.routes.map(item => item.id === route.id ? { ...item, modelId: event.target.value } : item) })}>
                        <option value="">{isEn ? 'Select a model' : '请选择模型'}</option>
                        {route.modelId && !models.some(model => model.id === route.modelId) && <option value={route.modelId}>{route.modelId} · {isEn ? 'not in catalog' : '当前列表中不可用'}</option>}
                        {models.map(model => <option key={model.id} value={model.id}>{model.id}{model.name && model.name !== model.id ? ` · ${model.name}` : ''}</option>)}
                    </select>
                </label>
                <p className="text-xs text-muted-foreground break-all">{isEn ? 'Client request ID: ' : '客户端请求 ID：'}{desktopClientModelId(route)}</p>
            </div>)}
            <Button variant="outline" onClick={addRoute} disabled={input.routes.length >= 50}><Plus className="h-4 w-4" />{isEn ? 'Add model entry' : '添加模型条目'}</Button>
        </fieldset>
        {missingModels && !loading && <p className="text-xs text-warning">{isEn ? 'Select an available target for each role. Missing roles are not silently substituted.' : '请为每档选择可用模型；缺少对应档位时不会自动替换为其他模型。'}</p>}
        {error && <p role="alert" className="rounded-lg bg-destructive/10 text-destructive p-3 text-sm break-words">{error}</p>}
        {message && <p role="status" className="rounded-lg bg-success/10 p-3 text-sm">{message}</p>}
        {preview && <div className="rounded-xl border p-4 space-y-3">
            <h4 className="font-medium">{isEn ? 'Review changes' : '确认写入内容'}</h4>
            <p className="font-mono text-xs break-all">{preview.proxyOrigin}</p>
            {preview.models.map(model => <p key={model} className="text-xs break-all">{model}</p>)}
            {preview.files.map(file => <div key={file.path} className="text-xs border-t pt-2 space-y-1">
                <p className="font-mono break-all">{file.path}</p>
                <p className="text-muted-foreground">{!file.changed ? (isEn ? 'Unchanged' : '无需更改') : file.exists ? (isEn ? 'Update with backup' : '备份后更新') : (isEn ? 'Create' : '新建')} · {file.fields.join(', ')}</p>
            </div>)}
            {preview.warnings.map(warning => <p key={warning} className="text-xs text-warning">{warning}</p>)}
        </div>}
        <div className="flex justify-end gap-2">
            <Button variant="outline" disabled={busy || loading || !ready || missingModels || pending} onClick={() => run('preview')}>{busy && <Loader2 className="h-4 w-4 animate-spin" />}{isEn ? 'Preview configuration' : '预览配置'}</Button>
            <Button disabled={busy || loading || !preview || pending} onClick={() => run('apply')}>{isEn ? 'Apply 3P gateway' : '应用 3P 网关配置'}</Button>
        </div>
        {recoverable.length > 0 && <details className="rounded-xl border p-3 text-sm" open={pending || undefined}>
            <summary className="cursor-pointer">{isEn ? 'Backups and recovery' : '备份与恢复'} ({recoverable.length})</summary>
            <p className="text-xs text-muted-foreground my-2">{isEn ? 'Restores all files changed by the selected operation, including model routes. External edits block restoration.' : '恢复所选操作修改的全部文件（含模型映射）。文件若被外部改动，会阻止恢复。'}</p>
            <select aria-label={isEn ? 'Operation to restore' : '选择恢复记录'} className={controlClass} value={restoreId} disabled={busy} onChange={event => setRestoreId(event.target.value)}>
                <option value="">{isEn ? 'Select an operation' : '选择操作记录'}</option>
                {recoverable.map(operation => <option key={operation.id} value={operation.id}>{operation.createdAt} · {operation.status}</option>)}
            </select>
            {restoreId && <div className="mt-2 space-y-1">
                {recoverable.find(operation => operation.id === restoreId)?.paths.map(path => <p key={path} className="text-xs font-mono break-all">{path}</p>)}
                <Button variant="outline" size="sm" disabled={busy} onClick={() => run('restore')}><RotateCcw className="h-4 w-4" />{isEn ? 'Restore these files' : '恢复上述文件'}</Button>
            </div>}
        </details>}
    </div>
}

// Kiro-account-manager/src/renderer-vue/src/components/proxy/ClaudeDesktopConfig.vue
<script setup>
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { UiAlert, UiButton, UiCard, UiField, UiInput, UiRadio, UiSelect } from '@lingyzh/ui'
import { Plus, RotateCcw, Trash2 } from 'lucide-vue-next'
import {
    defaultDesktopRoutes,
    desktopModelName,
    desktopClientModelId,
    DESKTOP_ROLE_IDS
} from '../../../../shared/desktopConfig'
import { toIpcData } from '../../lib/ipcData'

const props = defineProps({
    models: { type: Array, required: true },
    loading: { type: Boolean, required: true },
    isEn: { type: Boolean, required: true },
    busy: { type: Boolean, required: true }
})
const emit = defineEmits(['busy-change', 'reload'])
const input = ref(defaultDesktopRoutes([]))
const ready = ref(false)
const preview = ref(null)
const operations = ref([])
const error = ref('')
const message = ref('')
const restoreId = ref('')
const working = ref(false)
const modelKey = computed(() => JSON.stringify(props.models))
const missingModels = computed(() =>
    input.value.routes.some((route) => !props.models.some((model) => model.id === route.modelId))
)
const recoverable = computed(() =>
    operations.value.filter((operation) => operation.status !== 'restored')
)
const pending = computed(() =>
    recoverable.value.some((operation) => operation.status === 'pending')
)
const selectedOperation = computed(() =>
    recoverable.value.find((operation) => operation.id === restoreId.value)
)
let initialized = false
let generation = 0
let mounted = true

function change(next) {
    initialized = true
    input.value = next
    preview.value = null
    error.value = ''
    message.value = ''
}

function updateRoute(routeId, updates) {
    change({
        ...input.value,
        routes: input.value.routes.map((route) =>
            route.id === routeId ? { ...route, ...updates } : route
        )
    })
}

function changeFamily(route, family) {
    const id = `${DESKTOP_ROLE_IDS[family]}-kam-${crypto.randomUUID().slice(0, 8)}`
    change({
        ...input.value,
        routes: input.value.routes.map((item) =>
            item.id === route.id ? { ...item, family, id } : item
        ),
        defaultRouteId: input.value.defaultRouteId === route.id ? id : input.value.defaultRouteId
    })
}

function addRoute() {
    if (input.value.routes.length >= 50) return
    let suffix = 2
    while (
        input.value.routes.some((route) => route.id === `${DESKTOP_ROLE_IDS.sonnet}-kam-${suffix}`)
    )
        suffix += 1
    change({
        ...input.value,
        routes: [
            ...input.value.routes,
            {
                id: `${DESKTOP_ROLE_IDS.sonnet}-kam-${suffix}`,
                family: 'sonnet',
                label: props.isEn ? `Model ${suffix}` : `模型 ${suffix}`,
                modelId: ''
            }
        ]
    })
}

function removeRoute(routeId) {
    const routes = input.value.routes.filter((route) => route.id !== routeId)
    change({
        ...input.value,
        routes,
        defaultRouteId:
            input.value.defaultRouteId === routeId ? routes[0].id : input.value.defaultRouteId
    })
}

async function refreshOperations(refreshInput = false, current = generation) {
    const result = await window.api.proxyDesktopState()
    if (!mounted || current !== generation) return
    if (!result.success) throw new Error(result.error)
    operations.value = result.data.operations || []
    if (refreshInput) {
        input.value = result.data.input || defaultDesktopRoutes(props.models)
        initialized = true
        preview.value = null
    }
}

async function loadState() {
    const current = ++generation
    try {
        const result = await window.api.proxyDesktopState()
        if (!mounted || current !== generation) return
        if (!result.success) throw new Error(result.error)
        if (result.data.input) {
            initialized = true
            input.value = result.data.input
        }
        operations.value = result.data.operations || []
        ready.value = true
    } catch (cause) {
        if (mounted && current === generation)
            error.value = cause instanceof Error ? cause.message : String(cause)
    }
}

async function run(action) {
    if (working.value || !ready.value) return
    if (action === 'apply' && !preview.value) return
    if (action === 'restore' && !restoreId.value) return
    const current = generation
    const inputRevision = input.value
    const catalogRevision = modelKey.value
    working.value = true
    emit('busy-change', true)
    error.value = ''
    message.value = ''
    try {
        if (action === 'preview') {
            const result = await window.api.proxyDesktopPreview(toIpcData(input.value))
            if (!mounted || current !== generation) return
            if (!result.success) throw new Error(result.error)
            if (inputRevision === input.value && catalogRevision === modelKey.value)
                preview.value = result.data
        } else if (action === 'apply') {
            const token = preview.value.token
            const result = await window.api.proxyDesktopApply(token)
            if (!mounted || current !== generation) return
            preview.value = null
            if (!result.success) throw new Error(result.error)
            message.value = props.isEn
                ? 'Configuration written. Start the KAM proxy, then launch Claude Desktop. Live inference has not been tested.'
                : '配置已写入。先启动 KAM 反代，再启动 Claude Desktop；尚未验证真实推理请求。'
            await refreshOperations(false, current)
        } else {
            const operationId = restoreId.value
            const result = await window.api.proxyDesktopRestore(operationId)
            if (!mounted || current !== generation) return
            if (!result.success) throw new Error(result.error)
            restoreId.value = ''
            preview.value = null
            message.value = props.isEn
                ? 'Restored the files to their state before this operation.'
                : '已恢复到此次操作之前的文件状态。'
            await refreshOperations(true, current)
        }
    } catch (cause) {
        if (mounted && current === generation) {
            error.value = cause instanceof Error ? cause.message : String(cause)
            await refreshOperations(false, current).catch(() => {})
        }
    } finally {
        working.value = false
        if (mounted && current === generation) emit('busy-change', false)
    }
}

watch(modelKey, () => {
    preview.value = null
    if (ready.value && props.models.length && !initialized) {
        initialized = true
        input.value = defaultDesktopRoutes(props.models)
    }
})
watch(ready, (value) => {
    if (value && props.models.length && !initialized) {
        initialized = true
        input.value = defaultDesktopRoutes(props.models)
    }
})
void loadState()
onBeforeUnmount(() => {
    mounted = false
    generation += 1
    emit('busy-change', false)
})
</script>

<template>
    <div class="kam-desktop-config" data-testid="desktop-config">
        <UiCard density="compact">
            <h3>
                {{
                    isEn
                        ? 'Claude Desktop · First-launch gateway setup'
                        : 'Claude Desktop · 首次启动网关配置'
                }}
            </h3>
            <p class="kam-muted">
                {{
                    isEn
                        ? 'Creates and activates a dedicated KAM 3P profile. Each menu entry maps to the actual target model below; other clients are unaffected.'
                        : '创建并选中独立的 KAM 3P 配置。每个菜单条目映射到下方实际目标模型，不影响其他客户端。'
                }}
            </p>
            <p class="kam-muted">
                {{
                    isEn
                        ? 'Apply before first launch, or fully quit Desktop first. Existing MCP, preferences and other gateway profiles are preserved.'
                        : '可在首次启动前配置；已运行时请先完全退出 Desktop。保留已有 MCP、偏好和其他网关配置。'
                }}
            </p>
        </UiCard>
        <fieldset :disabled="busy || !ready" class="kam-desktop-routes">
            <div class="kam-actions">
                <strong>{{ isEn ? 'Desktop model menu' : 'Desktop 模型菜单' }}</strong>
                <UiButton
                    variant="secondary"
                    size="sm"
                    :disabled="loading || busy"
                    data-testid="desktop-reload"
                    @click="emit('reload')"
                    >{{ isEn ? 'Reload models' : '刷新模型' }}</UiButton
                >
            </div>
            <UiCard
                v-for="(route, index) in input.routes"
                :key="route.id"
                density="compact"
                :data-testid="`desktop-route-${index}`"
            >
                <div class="kam-actions">
                    <UiRadio
                        :model-value="input.defaultRouteId"
                        :value="route.id"
                        name="desktop-default-model"
                        @update:model-value="change({ ...input, defaultRouteId: route.id })"
                        >{{
                            input.defaultRouteId === route.id
                                ? isEn
                                    ? 'Default model'
                                    : '默认模型'
                                : isEn
                                  ? 'Set as default'
                                  : '设为默认'
                        }}</UiRadio
                    >
                    <UiButton
                        v-if="index >= 3"
                        variant="ghost"
                        size="sm"
                        :aria-label="isEn ? 'Remove model' : '删除模型'"
                        :data-testid="`desktop-remove-${index}`"
                        @click="removeRoute(route.id)"
                        ><Trash2 :size="16"
                    /></UiButton>
                </div>
                <div class="kam-desktop-route-fields">
                    <UiField :label="isEn ? 'Role' : '档位'">
                        <UiSelect
                            :model-value="route.family"
                            :disabled="index < 3"
                            :data-testid="`desktop-family-${index}`"
                            @update:model-value="changeFamily(route, $event)"
                            ><option value="opus">Opus</option>
                            <option value="sonnet">Sonnet</option>
                            <option value="haiku">Haiku</option></UiSelect
                        >
                    </UiField>
                    <UiField :label="isEn ? 'Menu label' : '菜单名称'"
                        ><UiInput
                            :model-value="desktopModelName(route.modelId)"
                            readonly
                            :data-testid="`desktop-label-${index}`"
                    /></UiField>
                </div>
                <UiField :label="isEn ? 'Actual target model' : '实际调用的模型'">
                    <UiSelect
                        :model-value="route.modelId"
                        :data-testid="`desktop-target-${index}`"
                        @update:model-value="updateRoute(route.id, { modelId: $event })"
                    >
                        <option value="">{{ isEn ? 'Select a model' : '请选择模型' }}</option>
                        <option
                            v-if="
                                route.modelId && !models.some((model) => model.id === route.modelId)
                            "
                            :value="route.modelId"
                        >
                            {{ route.modelId }} · {{ isEn ? 'not in catalog' : '当前列表中不可用' }}
                        </option>
                        <option v-for="model in models" :key="model.id" :value="model.id">
                            {{ model.id
                            }}{{ model.name && model.name !== model.id ? ` · ${model.name}` : '' }}
                        </option>
                    </UiSelect>
                </UiField>
                <p class="kam-muted kam-mono">
                    {{ isEn ? 'Client request ID: ' : '客户端请求 ID：'
                    }}{{ desktopClientModelId(route) }}
                </p>
            </UiCard>
            <UiButton
                variant="secondary"
                :disabled="input.routes.length >= 50"
                data-testid="desktop-add-route"
                @click="addRoute"
                ><Plus :size="16" />{{ isEn ? 'Add model entry' : '添加模型条目' }}</UiButton
            >
        </fieldset>
        <UiAlert
            v-if="missingModels && !loading"
            tone="warning"
            :title="isEn ? 'Missing target models' : '缺少目标模型'"
            >{{
                isEn
                    ? 'Select an available target for each role. Missing roles are not silently substituted.'
                    : '请为每档选择可用模型；缺少对应档位时不会自动替换为其他模型。'
            }}</UiAlert
        >
        <UiAlert
            v-if="error"
            tone="error"
            :title="isEn ? 'Configuration failed' : '配置失败'"
            data-testid="desktop-error"
            >{{ error }}</UiAlert
        >
        <UiButton
            v-if="!ready && error"
            variant="secondary"
            data-testid="desktop-retry-state"
            @click="loadState"
            >{{ isEn ? 'Retry loading' : '重试加载' }}</UiButton
        >
        <UiAlert v-if="message" tone="success" :title="isEn ? 'Completed' : '已完成'">{{
            message
        }}</UiAlert>
        <UiCard v-if="preview" density="compact" data-testid="desktop-preview">
            <h4>{{ isEn ? 'Review changes' : '确认写入内容' }}</h4>
            <p class="kam-mono">{{ preview.proxyOrigin }}</p>
            <p v-for="model in preview.models" :key="model">{{ model }}</p>
            <div v-for="file in preview.files" :key="file.path">
                <p class="kam-mono">{{ file.path }}</p>
                <p class="kam-muted">
                    {{
                        !file.changed
                            ? isEn
                                ? 'Unchanged'
                                : '无需更改'
                            : file.exists
                              ? isEn
                                  ? 'Update with backup'
                                  : '备份后更新'
                              : isEn
                                ? 'Create'
                                : '新建'
                    }}
                    · {{ file.fields.join(', ') }}
                </p>
            </div>
            <UiAlert v-for="warning in preview.warnings" :key="warning" tone="warning">{{
                warning
            }}</UiAlert>
        </UiCard>
        <div class="kam-actions kam-desktop-actions">
            <UiButton
                variant="secondary"
                :disabled="busy || loading || !ready || missingModels || pending"
                data-testid="desktop-preview-action"
                @click="run('preview')"
                >{{ isEn ? 'Preview configuration' : '预览配置' }}</UiButton
            >
            <UiButton
                :disabled="busy || loading || !preview || pending"
                data-testid="desktop-apply"
                @click="run('apply')"
                >{{ isEn ? 'Apply 3P gateway' : '应用 3P 网关配置' }}</UiButton
            >
        </div>
        <details
            v-if="recoverable.length"
            :open="pending || undefined"
            data-testid="desktop-operations"
        >
            <summary>
                {{ isEn ? 'Backups and recovery' : '备份与恢复' }} ({{ recoverable.length }})
            </summary>
            <p class="kam-muted">
                {{
                    isEn
                        ? 'Restores all files changed by the selected operation, including model routes. External edits block restoration.'
                        : '恢复所选操作修改的全部文件（含模型映射）。文件若被外部改动，会阻止恢复。'
                }}
            </p>
            <UiSelect
                v-model="restoreId"
                :aria-label="isEn ? 'Operation to restore' : '选择恢复记录'"
                data-testid="desktop-restore-operation"
                ><option value="">{{ isEn ? 'Select an operation' : '选择操作记录' }}</option>
                <option v-for="operation in recoverable" :key="operation.id" :value="operation.id">
                    {{ operation.createdAt }} · {{ operation.status }}
                </option></UiSelect
            >
            <div v-if="selectedOperation">
                <p v-for="path in selectedOperation.paths" :key="path" class="kam-mono">
                    {{ path }}
                </p>
                <UiButton
                    variant="secondary"
                    size="sm"
                    :disabled="busy"
                    data-testid="desktop-restore"
                    @click="run('restore')"
                    ><RotateCcw :size="16" />{{
                        isEn ? 'Restore these files' : '恢复上述文件'
                    }}</UiButton
                >
            </div>
        </details>
    </div>
</template>

<style scoped>
.kam-desktop-config,
.kam-desktop-routes {
    display: grid;
    gap: 16px;
    min-width: 0;
}
.kam-desktop-route-fields {
    display: grid;
    grid-template-columns: minmax(100px, 1fr) minmax(0, 2fr);
    gap: 12px;
}
.kam-desktop-actions {
    justify-content: flex-end;
}
.kam-desktop-config :deep(p) {
    overflow-wrap: anywhere;
}
@media (max-width: 700px) {
    .kam-desktop-route-fields {
        grid-template-columns: 1fr;
    }
}
</style>
