// Kiro-account-manager/src/renderer/src/components/proxy/ClientConfigDialog.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertCircle, Bot, Check, Code2, Cpu, FileCog, Loader2, Settings2, Terminal, X, Sparkles, Workflow, type LucideIcon } from 'lucide-react'
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Select } from '../ui'
import { useAccountsStore } from '../../store/accounts'
import { ClaudeDesktopConfig } from './ClaudeDesktopConfig'
import { cn } from '@/lib/utils'

type ClientTarget = 'claudeCode' | 'opencode' | 'codex' | 'gemini' | 'hermes' | 'openclaw'

interface ModelInfo {
  id: string
  name: string
  description?: string
  inputTypes?: string[]
  maxInputTokens?: number | null
  maxOutputTokens?: number | null
}

interface ClientConfigDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  isEn: boolean
}

interface ClientOption {
  id: ClientTarget
  name: string
  description: string
  icon: LucideIcon
}

interface ConfigureResult {
  client: ClientTarget
  success: boolean
  paths: string[]
  backupPaths: string[]
  error?: string
}

const clientLabels: Record<ClientTarget, string> = {
  claudeCode: 'Claude Code',
  opencode: 'OpenCode',
  codex: 'Codex CLI',
  gemini: 'Gemini CLI',
  hermes: 'Hermes',
  openclaw: 'OpenClaw'
}

export function ClientConfigDialog({ open, onOpenChange, isEn }: ClientConfigDialogProps) {
  const accounts = useAccountsStore(state => state.accounts)
  const activeAccountId = useAccountsStore(state => state.activeAccountId)
    const [desktopTab, setDesktopTab] = useState(true)
    const [desktopBusy, setDesktopBusy] = useState(false)
  const [models, setModels] = useState<ModelInfo[]>([])
  const [selectedModelId, setSelectedModelId] = useState('')
  const [selectedClients, setSelectedClients] = useState<ClientTarget[]>([])
  const [loadingModels, setLoadingModels] = useState(false)
  const [applying, setApplying] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [results, setResults] = useState<ConfigureResult[]>([])
  const [proxyBase, setProxyBase] = useState('')

  const clientOptions: ClientOption[] = useMemo(() => [
    {
      id: 'claudeCode',
      name: 'Claude Code',
      description: isEn ? 'Writes ANTHROPIC_BASE_URL, API key and default model' : '写入 ANTHROPIC_BASE_URL、API Key 和默认模型',
      icon: Bot
    },
    {
      id: 'opencode',
      name: 'OpenCode',
      description: isEn ? 'Adds Kiro provider and model metadata to opencode.json' : '向 opencode.json 添加 Kiro provider 和模型元数据',
      icon: Code2
    },
    {
      id: 'codex',
      name: 'Codex CLI',
      description: isEn ? 'Adds Kiro OpenAI Responses provider' : '添加 Kiro OpenAI Responses provider',
      icon: Terminal
    },
    {
      id: 'gemini',
      name: 'Gemini CLI',
      description: isEn ? 'Writes .env and settings.json for Gemini v1beta' : '写入 .env 和 settings.json 配置 Gemini v1beta',
      icon: Sparkles
    },
    {
      id: 'hermes',
      name: 'Hermes',
      description: isEn ? 'Adds Kiro provider to config.yaml' : '向 config.yaml 添加 Kiro provider',
      icon: Workflow
    },
    {
      id: 'openclaw',
      name: 'OpenClaw',
      description: isEn ? 'Adds Kiro provider to openclaw.json' : '向 openclaw.json 添加 Kiro provider',
      icon: Settings2
    }
  ], [isEn])

  const selectedModel = models.find(model => model.id === selectedModelId)

  const loadModels = useCallback(async () => {
    setLoadingModels(true)
    setError(null)
    setResults([])
    try {
      // 优先从代理服务获取模型（与"查看模型"一致）
      const proxyModels = await window.api.proxyGetModels()
      if (proxyModels.success && proxyModels.models.length > 0) {
        setModels(proxyModels.models)
        setSelectedModelId(current => proxyModels.models.some(model => model.id === current) ? current : proxyModels.models[0].id)
        return
      }

      // 代理未启动或无模型时，回退到账号直连
      const activeAccount = activeAccountId ? accounts.get(activeAccountId) : undefined
      const account = activeAccount?.status === 'active' && activeAccount.credentials?.accessToken
        ? activeAccount
        : Array.from(accounts.values()).find(item => item.status === 'active' && item.credentials?.accessToken)
      if (account) {
        const accountModels = await window.api.accountGetModels(
          account.credentials.accessToken,
          account.credentials.region || 'us-east-1',
          account.profileArn,
          account.machineId,
          account.credentials.provider || account.idp,
          account.credentials.authMethod,
          account.id
        )
        if (accountModels.success && accountModels.models.length > 0) {
          setModels(accountModels.models)
          setSelectedModelId(current => accountModels.models.some(model => model.id === current) ? current : accountModels.models[0]?.id || '')
          return
        }
      }

      setModels([])
      setSelectedModelId('')
      setError(isEn ? 'No models were loaded. Please check whether the account is active and try reloading.' : '未加载到模型，请确认账号已激活后重新加载。')
    } catch (err) {
      setModels([])
      setSelectedModelId('')
      setError(err instanceof Error ? err.message : (isEn ? 'Failed to load models' : '加载模型失败'))
    } finally {
      setLoadingModels(false)
    }
  }, [accounts, activeAccountId, isEn])

  useEffect(() => {
    if (open) {
      loadModels()
    }
  }, [open, loadModels])

  if (!open) return null

  const toggleClient = (client: ClientTarget) => {
    setResults([])
    setSelectedClients(current => current.includes(client) ? current.filter(item => item !== client) : [...current, client])
  }

  const applyConfig = async () => {
    if (!selectedModelId) {
      setError(isEn ? 'Please select a model' : '请选择模型')
      return
    }
    if (selectedClients.length === 0) {
      setError(isEn ? 'Please select at least one client' : '请至少选择一个客户端')
      return
    }

    setApplying(true)
    setError(null)
    setResults([])
    try {
      const result = await window.api.proxyConfigureClients({
        clients: selectedClients,
        modelId: selectedModelId,
        modelName: selectedModel?.name,
        models: models.map(model => ({
          id: model.id,
          name: model.name,
          inputTypes: model.inputTypes,
          maxInputTokens: model.maxInputTokens,
          maxOutputTokens: model.maxOutputTokens
        }))
      })
      setProxyBase(result.openaiBaseUrl || result.proxyOrigin)
      setResults(result.results)
      if (!result.success) {
        setError(result.error || (isEn ? 'Some clients failed to configure' : '部分客户端配置失败'))
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : (isEn ? 'Failed to configure clients' : '配置客户端失败'))
    } finally {
      setApplying(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/50" onClick={() => !(desktopBusy || applying) && onOpenChange(false)} />
      <Card className="relative w-[780px] max-w-[calc(100vw-2rem)] max-h-[85vh] shadow-2xl border-0 overflow-hidden animate-in fade-in zoom-in-95 duration-200 glass-card-strong">
        <CardHeader className="pb-4 border-b sticky top-0 z-10">
          <div className="flex items-center justify-between">
            <CardTitle className="text-xl flex items-center gap-3">
              <div className="p-2 rounded-xl bg-primary/10">
                <Settings2 className="h-6 w-6 text-primary" />
              </div>
              <div>
                <span className="font-bold">{isEn ? 'One-Click Client Configuration' : '一键配置客户端'}</span>
                <div className="flex items-center gap-2 mt-1">
                  <Badge className="bg-primary/10 text-primary border-primary/20 font-semibold">
                    {selectedClients.length} {isEn ? 'selected' : '个已选择'}
                  </Badge>
                  {proxyBase && (
                    <Badge variant="secondary" className="text-xs border-0">
                      {proxyBase}
                    </Badge>
                  )}
                </div>
              </div>
            </CardTitle>
            <Button variant="ghost" size="icon" className="h-9 w-9 rounded-lg hover:bg-red-500 hover:text-white transition-colors" onClick={() => !(desktopBusy || applying) && onOpenChange(false)}>
              <X className="h-5 w-5" />
            </Button>
          </div>
        </CardHeader>
        <CardContent className="p-4">
            <div className="flex gap-2 mb-4">
                <Button variant={desktopTab ? 'default' : 'outline'} disabled={desktopBusy || applying} onClick={() => setDesktopTab(true)}>Claude Desktop</Button>
                <Button variant={!desktopTab ? 'default' : 'outline'} disabled={desktopBusy || applying} onClick={() => setDesktopTab(false)}>{isEn ? 'Other clients' : '其他客户端'}</Button>
            </div>
          <div className="max-h-[calc(85vh-190px)] overflow-y-auto pr-2 space-y-4">
            {desktopTab ? <ClaudeDesktopConfig models={models} loading={loadingModels} isEn={isEn} busy={desktopBusy} onBusyChange={setDesktopBusy} onReload={loadModels} /> : <>
            <p className="text-sm text-muted-foreground">{isEn ? 'The selected model becomes the client default model.' : '此处选择的模型会写入客户端配置，作为客户端默认模型。'}</p>
            <div className="rounded-xl border bg-background p-4 space-y-3">
              <div className="flex items-center justify-between gap-3">
                <div className="flex items-center gap-2">
                  <Cpu className="h-4 w-4 text-primary" />
                  <span className="font-medium">{isEn ? 'Model' : '模型'}</span>
                </div>
                <Button variant="outline" size="sm" onClick={loadModels} disabled={loadingModels}>
                  {loadingModels ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileCog className="h-4 w-4" />}
                  {isEn ? 'Reload' : '重新加载'}
                </Button>
              </div>
              {loadingModels ? (
                <div className="flex items-center gap-2 text-sm text-muted-foreground py-2">
                  <Loader2 className="h-4 w-4 animate-spin" />
                  {isEn ? 'Loading models...' : '加载模型中...'}
                </div>
              ) : models.length > 0 ? (
                <div className="space-y-2">
                  <Select
                    value={selectedModelId}
                    options={models.map(model => ({
                      value: model.id,
                      label: model.id,
                      description: model.name && model.name !== model.id ? model.name : model.description
                    }))}
                    onChange={value => {
                      setSelectedModelId(value)
                      setResults([])
                    }}
                    placeholder={isEn ? 'Select model' : '选择模型'}
                  />
                  {selectedModel && (
                    <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                      <Badge variant="secondary" className="border-0">{selectedModel.name || selectedModel.id}</Badge>
                      {selectedModel.inputTypes?.map(type => (
                        <Badge key={type} variant="secondary" className="border-0">{type}</Badge>
                      ))}
                    </div>
                  )}
                </div>
              ) : (
                <div className="text-sm text-muted-foreground py-2">{isEn ? 'No models loaded' : '暂无模型'}</div>
              )}
            </div>

            <div className="grid grid-cols-3 gap-3">
              {clientOptions.map(option => {
                const Icon = option.icon
                const checked = selectedClients.includes(option.id)
                return (
                  <button
                    key={option.id}
                    type="button"
                    onClick={() => toggleClient(option.id)}
                    className={cn(
                      'text-left rounded-xl border p-4 transition-all hover:border-primary/50 hover:bg-primary/5',
                      checked ? 'border-primary/50 bg-primary/10 shadow-sm' : 'bg-background'
                    )}
                  >
                    <div className="flex items-start justify-between gap-2 mb-3">
                      <div className="p-2 rounded-lg bg-primary/10">
                        <Icon className="h-5 w-5 text-primary" />
                      </div>
                      <div className={cn('h-5 w-5 rounded-full border flex items-center justify-center', checked ? 'bg-primary border-primary text-primary-foreground' : 'border-muted-foreground/40')}>
                        {checked && <Check className="h-3.5 w-3.5" />}
                      </div>
                    </div>
                    <div className="font-semibold text-sm mb-1">{option.name}</div>
                    <div className="text-xs text-muted-foreground leading-relaxed">{option.description}</div>
                  </button>
                )
              })}
            </div>

            <div className="rounded-xl border border-warning/30 bg-warning/10 p-3 flex items-start gap-2 text-sm text-warning">
              <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" />
              <div>{isEn ? 'Existing client files are merged and backed up before writing.' : '写入时会合并原配置并先创建备份。'}</div>
            </div>

            {error && (
              <div className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 flex items-start gap-2 text-sm text-destructive">
                <AlertCircle className="h-4 w-4 mt-0.5 shrink-0" />
                <div>{error}</div>
              </div>
            )}

            {results.length > 0 && (
              <div className="space-y-2">
                {results.map(result => (
                  <div key={result.client} className={cn('rounded-xl border p-3 text-sm', result.success ? 'border-success/30 bg-success/10' : 'border-destructive/30 bg-destructive/10')}>
                    <div className="flex items-center justify-between gap-2 mb-2">
                      <span className="font-semibold">{clientLabels[result.client]}</span>
                      <Badge className={result.success ? 'bg-success/15 text-success border-success/20' : 'bg-destructive/15 text-destructive border-destructive/20'}>
                        {result.success ? (isEn ? 'Configured' : '已配置') : (isEn ? 'Failed' : '失败')}
                      </Badge>
                    </div>
                    {result.error ? (
                      <div className="text-xs text-destructive">{result.error}</div>
                    ) : (
                      <div className="space-y-1 text-xs text-muted-foreground">
                        {result.paths.map(path => <div key={path} className="font-mono break-all">{path}</div>)}
                        {result.backupPaths.length > 0 && <div>{isEn ? 'Backups created' : '已创建备份'}: {result.backupPaths.length}</div>}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}

            <div className="flex justify-end gap-2 pt-2">
              <Button variant="outline" onClick={() => !(desktopBusy || applying) && onOpenChange(false)} disabled={applying}>{isEn ? 'Close' : '关闭'}</Button>
              <Button onClick={applyConfig} disabled={loadingModels || applying || !selectedModelId || selectedClients.length === 0}>
                {applying ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}
                {applying ? (isEn ? 'Configuring...' : '配置中...') : (isEn ? 'Apply Configuration' : '应用配置')}
              </Button>
            </div>
            </>}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// Kiro-account-manager/src/renderer-vue/src/components/proxy/ClientConfigDialog.vue
<script setup>
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import {
    UiAlert,
    UiBadge,
    UiButton,
    UiCard,
    UiCheckbox,
    UiDialog,
    UiField,
    UiSelect
} from '@lingyzh/ui'
import { Check, RefreshCw } from 'lucide-vue-next'
import { useAccountsStore } from '../../stores/accounts'
import { useTranslation } from '../../composables/useTranslation'
import { toIpcData } from '../../lib/ipcData'
import ClaudeDesktopConfig from './ClaudeDesktopConfig.vue'

const props = defineProps({
    open: { type: Boolean, required: true },
    isEn: { type: Boolean, default: undefined }
})
const emit = defineEmits(['update:open'])
const accounts = useAccountsStore()
const { actualLanguage } = useTranslation()
const isEn = computed(() => props.isEn ?? actualLanguage.value === 'en')
const desktopTab = ref(true)
const desktopBusy = ref(false)
const models = ref([])
const selectedModelId = ref('')
const selectedClients = ref([])
const loadingModels = ref(false)
const applying = ref(false)
const error = ref('')
const results = ref([])
const proxyBase = ref('')
const selectedModel = computed(() =>
    models.value.find((model) => model.id === selectedModelId.value)
)
const clientOptions = computed(() => [
    {
        id: 'claudeCode',
        name: 'Claude Code',
        description: isEn.value
            ? 'Writes ANTHROPIC_BASE_URL, API key and default model'
            : '写入 ANTHROPIC_BASE_URL、API Key 和默认模型'
    },
    {
        id: 'opencode',
        name: 'OpenCode',
        description: isEn.value
            ? 'Adds Kiro provider and model metadata to opencode.json'
            : '向 opencode.json 添加 Kiro provider 和模型元数据'
    },
    {
        id: 'codex',
        name: 'Codex CLI',
        description: isEn.value
            ? 'Adds Kiro OpenAI Responses provider'
            : '添加 Kiro OpenAI Responses provider'
    },
    {
        id: 'gemini',
        name: 'Gemini CLI',
        description: isEn.value
            ? 'Writes .env and settings.json for Gemini v1beta'
            : '写入 .env 和 settings.json 配置 Gemini v1beta'
    },
    {
        id: 'hermes',
        name: 'Hermes',
        description: isEn.value
            ? 'Adds Kiro provider to config.yaml'
            : '向 config.yaml 添加 Kiro provider'
    },
    {
        id: 'openclaw',
        name: 'OpenClaw',
        description: isEn.value
            ? 'Adds Kiro provider to openclaw.json'
            : '向 openclaw.json 添加 Kiro provider'
    }
])
let generation = 0
let mounted = true

function close() {
    if (desktopBusy.value || applying.value) return
    emit('update:open', false)
}

function changeTab(next) {
    if (desktopBusy.value || applying.value) return
    desktopTab.value = next
}

function toggleClient(id) {
    if (applying.value) return
    results.value = []
    selectedClients.value = selectedClients.value.includes(id)
        ? selectedClients.value.filter((client) => client !== id)
        : [...selectedClients.value, id]
}

function chooseModel(id) {
    selectedModelId.value = id
    results.value = []
}

function chooseLoadedModels(entries) {
    models.value = entries
    if (!entries.some((model) => model.id === selectedModelId.value))
        selectedModelId.value = entries[0]?.id || ''
}

async function loadModels() {
    if (!props.open || loadingModels.value) return
    const current = generation
    loadingModels.value = true
    error.value = ''
    results.value = []
    try {
        const proxyModels = await window.api.proxyGetModels()
        if (!mounted || !props.open || current !== generation) return
        if (proxyModels.success && proxyModels.models?.length) {
            chooseLoadedModels(proxyModels.models)
            return
        }
        const active = accounts.activeAccountId
            ? accounts.accounts.get(accounts.activeAccountId)
            : undefined
        const eligible = (item) => item?.status === 'active' && item.credentials?.accessToken
        const account = eligible(active)
            ? active
            : Array.from(accounts.accounts.values()).find(eligible)
        if (account) {
            const accountModels = await window.api.accountGetModels(
                account.credentials.accessToken,
                account.credentials.region || 'us-east-1',
                account.profileArn,
                account.machineId,
                account.credentials.provider || account.idp,
                account.credentials.authMethod,
                account.id
            )
            if (!mounted || !props.open || current !== generation) return
            if (accountModels.success && accountModels.models?.length) {
                chooseLoadedModels(accountModels.models)
                return
            }
        }
        models.value = []
        selectedModelId.value = ''
        error.value = isEn.value
            ? 'No models were loaded. Please check whether the account is active and try reloading.'
            : '未加载到模型，请确认账号已激活后重新加载。'
    } catch (cause) {
        if (mounted && props.open && current === generation) {
            models.value = []
            selectedModelId.value = ''
            error.value = cause instanceof Error ? cause.message : String(cause)
        }
    } finally {
        if (mounted && props.open && current === generation) loadingModels.value = false
    }
}

async function applyConfig() {
    if (applying.value || desktopBusy.value) return
    if (!selectedModelId.value || !selectedClients.value.length) {
        error.value = !selectedModelId.value
            ? isEn.value
                ? 'Please select a model'
                : '请选择模型'
            : isEn.value
              ? 'Please select at least one client'
              : '请至少选择一个客户端'
        return
    }
    const current = generation
    applying.value = true
    error.value = ''
    results.value = []
    try {
        const result = await window.api.proxyConfigureClients(
            toIpcData({
                clients: selectedClients.value,
                modelId: selectedModelId.value,
                modelName: selectedModel.value?.name,
                models: models.value.map((model) => ({
                    id: model.id,
                    name: model.name,
                    inputTypes: model.inputTypes,
                    maxInputTokens: model.maxInputTokens,
                    maxOutputTokens: model.maxOutputTokens
                }))
            })
        )
        if (!mounted || !props.open || current !== generation) return
        proxyBase.value = result.openaiBaseUrl || result.proxyOrigin || ''
        results.value = result.results || []
        if (!result.success)
            error.value =
                result.error ||
                (isEn.value ? 'Some clients failed to configure' : '部分客户端配置失败')
    } catch (cause) {
        if (mounted && props.open && current === generation)
            error.value = cause instanceof Error ? cause.message : String(cause)
    } finally {
        if (mounted && props.open && current === generation) applying.value = false
    }
}

watch(
    () => props.open,
    (open) => {
        generation += 1
        if (open) void loadModels()
        else {
            loadingModels.value = false
            applying.value = false
            desktopBusy.value = false
        }
    },
    { immediate: true }
)
onBeforeUnmount(() => {
    mounted = false
    generation += 1
})
</script>

<template>
    <UiDialog
        :open="open"
        size="xl"
        scrollable
        :aria-label="isEn ? 'One-Click Client Configuration' : '一键配置客户端'"
        :content-label="isEn ? 'Client configuration' : '客户端配置'"
        data-testid="client-config-dialog"
        @update:open="
            (value) => {
                if (!value) close()
            }
        "
    >
        <template #header
            ><h2>{{ isEn ? 'One-Click Client Configuration' : '一键配置客户端' }}</h2>
            <UiBadge tone="accent"
                >{{ selectedClients.length }} {{ isEn ? 'selected' : '个已选择' }}</UiBadge
            ><UiBadge v-if="proxyBase" tone="neutral">{{ proxyBase }}</UiBadge></template
        >
        <div v-if="open" class="kam-dialog-content">
            <div class="kam-actions">
                <UiButton
                    :variant="desktopTab ? 'primary' : 'secondary'"
                    :disabled="desktopBusy || applying"
                    data-testid="client-tab-desktop"
                    @click="changeTab(true)"
                    >Claude Desktop</UiButton
                >
                <UiButton
                    :variant="!desktopTab ? 'primary' : 'secondary'"
                    :disabled="desktopBusy || applying"
                    data-testid="client-tab-others"
                    @click="changeTab(false)"
                    >{{ isEn ? 'Other clients' : '其他客户端' }}</UiButton
                >
            </div>
            <ClaudeDesktopConfig
                v-if="desktopTab"
                :models="models"
                :loading="loadingModels"
                :is-en="isEn"
                :busy="desktopBusy"
                @busy-change="desktopBusy = $event"
                @reload="loadModels"
            />
            <template v-else>
                <p class="kam-muted">
                    {{
                        isEn
                            ? 'The selected model becomes the client default model.'
                            : '此处选择的模型会写入客户端配置，作为客户端默认模型。'
                    }}
                </p>
                <UiCard density="compact">
                    <div class="kam-actions">
                        <strong>{{ isEn ? 'Model' : '模型' }}</strong
                        ><UiButton
                            variant="secondary"
                            size="sm"
                            :loading="loadingModels"
                            :disabled="loadingModels"
                            data-testid="client-reload-models"
                            @click="loadModels"
                            ><RefreshCw :size="16" />{{ isEn ? 'Reload' : '重新加载' }}</UiButton
                        >
                    </div>
                    <p v-if="loadingModels" class="kam-muted">
                        {{ isEn ? 'Loading models…' : '加载模型中…' }}
                    </p>
                    <UiField
                        v-else-if="models.length"
                        :label="isEn ? 'Available model' : '可用模型'"
                        ><UiSelect
                            :model-value="selectedModelId"
                            data-testid="client-model"
                            @update:model-value="chooseModel"
                            ><option v-for="model in models" :key="model.id" :value="model.id">
                                {{ model.id
                                }}{{
                                    model.name && model.name !== model.id ? ` · ${model.name}` : ''
                                }}
                            </option></UiSelect
                        ></UiField
                    >
                    <p v-else class="kam-muted">{{ isEn ? 'No models loaded' : '暂无模型' }}</p>
                    <div v-if="selectedModel" class="kam-actions">
                        <UiBadge tone="neutral">{{
                            selectedModel.name || selectedModel.id
                        }}</UiBadge
                        ><UiBadge
                            v-for="type in selectedModel.inputTypes || []"
                            :key="type"
                            tone="neutral"
                            >{{ type }}</UiBadge
                        >
                    </div>
                </UiCard>
                <div class="kam-client-grid">
                    <UiCard v-for="option in clientOptions" :key="option.id" density="compact"
                        ><UiCheckbox
                            :model-value="selectedClients.includes(option.id)"
                            :disabled="applying"
                            :data-testid="`client-select-${option.id}`"
                            @update:model-value="toggleClient(option.id)"
                            ><strong>{{ option.name }}</strong></UiCheckbox
                        >
                        <p class="kam-muted">{{ option.description }}</p></UiCard
                    >
                </div>
                <UiAlert tone="warning">{{
                    isEn
                        ? 'Existing client files are merged and backed up before writing.'
                        : '写入时会合并原配置并先创建备份。'
                }}</UiAlert>
                <UiAlert
                    v-if="error"
                    tone="error"
                    :title="isEn ? 'Configuration failed' : '配置失败'"
                    data-testid="client-config-error"
                    >{{ error }}</UiAlert
                >
                <div v-if="results.length" class="kam-client-results">
                    <UiCard v-for="result in results" :key="result.client" density="compact"
                        ><div class="kam-actions">
                            <strong>{{
                                clientOptions.find((option) => option.id === result.client)?.name ||
                                result.client
                            }}</strong
                            ><UiBadge :tone="result.success ? 'success' : 'error'">{{
                                result.success
                                    ? isEn
                                        ? 'Configured'
                                        : '已配置'
                                    : isEn
                                      ? 'Failed'
                                      : '失败'
                            }}</UiBadge>
                        </div>
                        <p v-if="result.error">{{ result.error }}</p>
                        <template v-else
                            ><p v-for="path in result.paths || []" :key="path" class="kam-mono">
                                {{ path }}
                            </p>
                            <p v-if="result.backupPaths?.length" class="kam-muted">
                                {{ isEn ? 'Backups created' : '已创建备份' }}:
                                {{ result.backupPaths.length }}
                            </p></template
                        ></UiCard
                    >
                </div>
                <div class="kam-actions kam-client-footer">
                    <UiButton variant="secondary" :disabled="applying" @click="close">{{
                        isEn ? 'Close' : '关闭'
                    }}</UiButton
                    ><UiButton
                        :loading="applying"
                        :disabled="
                            loadingModels || applying || !selectedModelId || !selectedClients.length
                        "
                        data-testid="client-apply"
                        @click="applyConfig"
                        ><Check :size="16" />{{
                            applying
                                ? isEn
                                    ? 'Configuring…'
                                    : '配置中…'
                                : isEn
                                  ? 'Apply Configuration'
                                  : '应用配置'
                        }}</UiButton
                    >
                </div>
            </template>
        </div>
        <template #footer
            ><UiButton variant="ghost" :disabled="desktopBusy || applying" @click="close">{{
                isEn ? 'Close' : '关闭'
            }}</UiButton></template
        >
    </UiDialog>
</template>

<style scoped>
.kam-client-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 12px;
}
.kam-client-results {
    display: grid;
    gap: 8px;
}
.kam-client-footer {
    justify-content: flex-end;
}
.kam-client-results :deep(p) {
    overflow-wrap: anywhere;
}
</style>
